### ISSUE TITLE
Banner uses a different font for ROOT than old website

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#10]
Not sure whether it's intentional.

Before:
![image](https://user-images.githubusercontent.com/10999034/83643183-04b4b400-a5b0-11ea-81fa-747e5637b940.png)

After:
![image](https://user-images.githubusercontent.com/10999034/83643217-0e3e1c00-a5b0-11ea-9336-b9221e7ae4a2.png)

**Comment by couet** [comment]
It is not. but which one is looking better ... just a matter os taste I guess ...

**Comment by Axel-Naumann** [comment]
Fairly close to Fira Sans: https://fonts.google.com/specimen/Fira+Sans?query=fira&preview.text=ROOT&preview.text_type=custom&sidebar.open&selection.family=Fira+Sans:wght@300
My estimate is it's Light / 300. @couet could you use that just for the logo text ("ROOT Data Analysis Framework"), please?

**Comment by Axel-Naumann** [comment]
We should also adjust the font used in doxygen: https://root.cern/doc/master/ where we currently use DejaVu Sans (in practice, for me - we ask for "Roboto") which is further away from the original logo font https://root.cern.ch/img/logos/ROOT_Logo/misc/logo_full-plus-text-hor.png

**Comment by amadio** [comment]
FWIW, the current logo uses a light version of [Open Sans](https://fonts.google.com/specimen/Open+Sans?preview.text=ROOT+Data+Analisys+Framework&preview.text_type=custom).
