### ISSUE TITLE
Dead link on main ROOT Reference page

### ISSUE THREAD

**Issue by FormalSymmetry** [root-project/web#1007]
The link `https://root.cern/doc/master/ROOT.qch.gz` to download the `.qch` offline reference manual for Qt Creator/Assistant is dead. The link is posted on the main reference page `https://root.cern/reference/`

Same applies for tag file.

**Comment by dpiparo** [comment]
thanks for this report.

**Comment by FormalSymmetry** [comment]
I'd like to claim that 5-σ discovery now :joy:

**Comment by FormalSymmetry** [comment]
I tried using the link again recently and have found that the link is still dead :slightly_frowning_face:
