### ISSUE TITLE
Introduce doxygen version switching mechanism

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#102]

**Comment by Axel-Naumann** [comment]
@couet please see https://github.com/root-project/doxyvers which also explains how to embed it into doxygen. I have "installed" the files into https://root.cern/doc/ - you should be able to "turn" it on by changing the header.

**Comment by Axel-Naumann** [comment]
To check whether the Doxygen change does what it should you can compare it with the sources of this "playground" of mine: http://axel.web.cern.ch/axel/doc/v620/classTHtml.html where I modified the Doxygen-generated page by hand.

**Comment by couet** [comment]
I made this PR. https://github.com/root-project/root/pull/5863
It shows the menu at the right place but more tuning is needed.

**Comment by eguiraud** [comment]
Hi, on the forum, users complain that their ROOT does not do what the reference says it does all the time. Please please add a big orange banner that says "you are looking at the documentation for ROOT master branch. To switch to the documentation for your version, use the button below".

**Comment by stwunsch** [comment]
As an example, here what scipy does:

![Screenshot from 2020-07-01 10-50-01](https://user-images.githubusercontent.com/6951222/86224059-acf67200-bb88-11ea-8559-9cd6722d876d.png)

**Comment by Axel-Naumann** [comment]
That's not this issue; please open a separate one. I'm not even sure it *is* an issue :-) The good news is: this issue here is fixed!
