### ISSUE TITLE
Add PR action to check links

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#103]
- correctness of links
- warn about doxygen links not going into master (only OK for release notes)
- warn about use of "root.cern.ch" instead of "root.cern"

**Comment by eguiraud** [comment]
#204 and #227 addressed the first point: correctness of links for all website pages except those under `/releases` is checked when a PR is submitted and on pushes to the gh-pages branch.

**Comment by eguiraud** [comment]
#269 fixed the third bullet point (and as github actions don't really have a "warn" mode afaict, a failed check simply makes the run fail).

@Axel-Naumann can you elaborate on bullet point 2? Do we really want to point to the docs for master from everywhere rather than to the latest release?

**Comment by Axel-Naumann** [comment]
As we will have the version switching mechanism, pointing to master gives it more visibility without a high usability issue. I think that's preferable; we can revisit if too many users complain?

**Comment by eguiraud** [comment]
Ah, forgot about the version-switching. On the forum, users complain that their ROOT does not do what the reference says it does all the time. I know it's off-topic for this issue, but please please add a big orange banner that says "you are looking at the documentation for ROOT master branch. To switch to the documentation for your version, use the button below".

**Comment by eguiraud** [comment]
I will add a check for bullet point 2 as soon as I have time
