### ISSUE TITLE
Write blog post on new PyROOT

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#105]

**Comment by etejedor** [comment]
Done here https://github.com/root-project/web/pull/160 (to be reviewed)

**Comment by stwunsch** [comment]
@Axel-Naumann This can be closed, I guess?

**Comment by etejedor** [comment]
@stwunsch if you reviewed the post and all is good, for me you can close (unless @Axel-Naumann wants to have a look too).

**Comment by stwunsch** [comment]
I had a look, looks great! @Axel-Naumann I'm closing, though feel free to reopen if you don't agree.
