### ISSUE TITLE
/reference is very hard to find

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#11]
The `Reference` button on the home page, as well as the `Reference guide` link in /manual`, link directly to master's doxygen ref guide.

Confusingly, the left-side navbar on `/manual`, instead, links to a `/reference` page that is otherwise impossible to access and that lists links for the doxygen docs for all versions.

**Comment by couet** [comment]
Yes on manual it gives a link to all the various version of the reference guides. May be the Nav bar in Manual should be named differently... some idea ? 'Reference Guides" .. with an "s" ...?

**Comment by eguiraud** [comment]
My point is that if I was a user looking for the reference guide for a particular ROOT version, I would not look at the bottom of the navbar of the `/manual` section :D

**Comment by couet** [comment]
yes but the reference guide is accessible from the home page and in many other places.  So what do you suggest with the link in the Nav bar ? we need to have a link somewhere to all the various versions of the ref guide.

**Comment by eguiraud** [comment]
> we need to have a link somewhere to all the various versions of the ref guide.

Yes, my point is that, currently, that link is very hard to find. Don't you agree?

> We should put it elsewhere ?

Yes, I think so

> where ?

I don't know, I hoped you would have an idea :smile:

**Comment by couet** [comment]
Of course it could be elsewhere.  I do not really know a better place for the time being. 
It is under the hat "Further information"... I think that's really what it is...

**Comment by eguiraud** [comment]
But why would I look under "Manual" for a list of reference guides in the first place, when there is a giant button "Reference" in the home page?

**Comment by couet** [comment]
Because the idea was (as a start) to try to mimic the old web site as far possible: in root.cern.ch the "Giant Button" points to the master version of the reference guide and to find the list of all the reference guides version you need to go in the Documentation pull menu .

**Comment by Axel-Naumann** [comment]
Let's integrate the version switching doxygen thingy - then we can get rid of `/reference` altogether? I don't specifically care about the versions <= 5.32.

**Comment by eguiraud** [comment]
The version-switching button has been integrated in doxygen. #329 removes `/reference` as per Axel's suggestion.

**Comment by couet** [comment]
5.34 is not visible from the drop-down menu at https://root.cern/doc/master/ 

I guess we can leave the dropdown menu as it is . Making publicity for very old releases
is not good I think. But we should also make sure one can find the old releases reference guides.

May be we should reactivate this page:https://root.cern/d/guides/reference-guide.html

To be more precise: seems to me that page can be put back in: https://root.cern/manual/
Under “further information"

If that’s ok with you I can do it.

**Comment by eguiraud** [comment]
I don't have a strong opinion. It would mean this issue is a "won't fix", so it can stay closed.

**Comment by couet** [comment]
I will propose a PR to reintegrate https://root.cern/d/guides/reference-guide.html

**Comment by eguiraud** [comment]
It's enough to `git revert` commit 64820fd8ed, see https://github.com/root-project/web/pull/329 that we discussed the other day

**Comment by couet** [comment]
I am done. I prefer to do a new commit because I will change a bit the text in the "reference page"

**Comment by couet** [comment]
PR: https://github.com/root-project/web/pull/343
