### ISSUE TITLE
Reduce content of "For Developers"

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#110]
The page is a (too) long list of random things; remove items that are not relevant anymore, or move them out to a "Useful Links" page.

**Comment by stwunsch** [comment]
Related to #74

**Comment by eguiraud** [comment]
The left-side navbar should offer those few "Useful Links". Currently it mirrors the body of the page almost 1:1, which does not make sense.

**Comment by couet** [comment]
I guess we are happy with that page now. Can we close this issue ?

**Comment by eguiraud** [comment]
Cannot comment on whether the content can be reduced further, but as a related issue: when landing on https://root.cern/for_developers, the same content is repeated three times: left-side navbar, page content and ToC are basically all the same.

I would suggest to only keep the left-side navbar, which helps navigating the section and stays fixed also when entering a subpage, and changing the page content to just say: "This section is intended for the ROOT developers and for people who want to contribute to the ROOT system. Check the navbar for several useful links".

**Comment by couet** [comment]
I agree the page body is the same as the left TOC. But each item gets its explanation. 
It is true that in that case, the "one this page" table on the right is not needed. It is not needed.
