### ISSUE TITLE
"Building ROOT": stale platforms

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#127]
https://root-project.github.io/web/download/building/ mentions
```
Supported platforms for building ROOTPermalink

    freebsd7 for FreeBSD 7.x with gcc >= 4.8
    linux for i386 Linux with gcc >= 4.8
    linuxx8664gcc for x86-64 Linux with gcc >= 4.8
    macosx for MacOS X >= 10.8 with clang
    openbsd for OpenBSD >= 5.x with gcc >= 4.8
```
That's complete bogus and should be just removed.

**Comment by eguiraud** [comment]
The content in `/download` is meant to be fully replaced by the content in `/install` (which does not mention that list of supported platforms)
