### ISSUE TITLE
Supported platforms mention configure-archs

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#128]
https://root-project.github.io/web/download/building_root/supported_platforms/ lists the old `configure` architecture names that serve no purpose. Reword, e.g.

"freebsd7 for FreeBSD 7.x with gcc >= 4.8" => "FreeBSD 7.x with gcc >= 4.8"

**Comment by Axel-Naumann** [comment]
The page has more problems - mentioning things "in preparation" that actually work. I'll take care of it.

**Comment by eguiraud** [comment]
note that the content under `/download` is supposed to be fully replaced by the content under `/install`. sorry for the confusion.

**Comment by eguiraud** [comment]
`/download` does not exist anymore
