### ISSUE TITLE
Change homepage HTML <title>

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#134]
Currently "ROOT", should be "ROOT data analysis framework"

**Comment by couet** [comment]
<title>ROOT</title> is taken from the config file _config.yml.

```
title                    : "ROOT"
title_separator          : "-"
subtitle                 : "Data Analysis Framework"
```

We need a to find a way to add the subtitle after  the title.

**Comment by Axel-Naumann** [comment]
Or make the subtitle empty and move "Data Analysis Framework" into "title"

**Comment by couet** [comment]
Yes, that's the first thing I tred but it looks ugly:
<img width="1065" alt="Screenshot 2020-06-10 at 08 57 00" src="https://user-images.githubusercontent.com/4697738/84236758-78971500-aaf8-11ea-8972-7add1475d95e.png">

**Comment by Axel-Naumann** [comment]
Eeew. Thanks.

**Comment by couet** [comment]
I am wondering if, at some point, for things like that, we might need some post processing script to modify directly the html files generated by Jekyll.

**Comment by eguiraud** [comment]
modifying the theme should be enough?

**Comment by couet** [comment]
The string in the <title> tag in the main html page comes from the the `_config.yml` file. It shows like like that in the final static version of the site:
```
<!-- begin _includes/seo.html --><title>ROOT</title>
<meta name="description" content="A modular scientific software toolkit ">
```
I am not sure this can be tweak from some changes in the theme.

**Comment by Axel-Naumann** [comment]
As it says, this is defined in minimal_mistake's `_includes/seo.html`

**Comment by Axel-Naumann** [comment]
Looking at this I think we should give the *homepage* a page title. I.e. keep "ROOT" as site title, but call the homepage "Data Analysis Framework"

**Comment by couet** [comment]
Yes editing `_includes/seo.html` seems the way to go. Looking at it.

**Comment by couet** [comment]
Now fixed in `_includes/seo.html` . The default title is a concatenation of the site.title and site.description.

**Comment by Axel-Naumann** [comment]
With the new frontpage also the title changed, to `ROOT: analyzing petabytes of data, scientifically. - ROOT`. Not super nice / ideal, but not terrible either. What do people think?

**Comment by couet** [comment]
I guess the title is fine now. Can we close this issue ?
