### ISSUE TITLE
Improve code highlighting theme

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#135]
Here a screenshot comparing the theme from the "dirt" skin to a (imho) more modern look with greyish colors.

What do you think?

![Screenshot from 2020-06-09 19-25-36](https://user-images.githubusercontent.com/6951222/84180477-d63f4900-aa87-11ea-8153-29881ad11e80.png)

**Comment by stwunsch** [comment]
In the right version also the background is completely white!

**Comment by stwunsch** [comment]
I'll put it in if you like it, this has to be done on the basis of the theme/skin.

**Comment by eguiraud** [comment]
My personal preference goes to the version on the right

**Comment by eguiraud** [comment]
Closed via https://github.com/root-project/minimal-mistakes/pull/1
