### ISSUE TITLE
Change icons

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#136]
I'm not a friend of the icons used for the forum, docs and so on. Here a version replacing the icons with the ones we have on root.cern:

What do you think? To me it looks like a better fit, though, personal preference at the best.

![Screenshot from 2020-06-09 19-41-39](https://user-images.githubusercontent.com/6951222/84181727-a1cc8c80-aa89-11ea-98aa-aa53fb880892.png)

**Comment by stwunsch** [comment]
And again, removed greenish color and added a white background on the right.

**Comment by Axel-Naumann** [comment]
My personal opinion: I like the new ones way better than the old ones (why a window frame?!) even though I'd be happy to see different icons than the new ones. They are just the obvious font-awesome icons, I guess... I.e. alternative proposals?

**Comment by pcanal** [comment]
No actual proposal here .. but the old icon having more than one color made them more lively.

**Comment by stwunsch** [comment]
@Axel-Naumann What about this?

![Screenshot from 2020-06-09 23-30-22](https://user-images.githubusercontent.com/6951222/84203214-5aee8f00-aaa9-11ea-8ac9-88194af14978.png)

**Comment by Axel-Naumann** [comment]
Nicer - but where did we get that reddish brown from? That's not a consistent ROOT color? Thanks for investing so much effort here, I bet people will appreciate!

**Comment by stwunsch** [comment]
It's kind of a complement to the blue, though not in the color palette of the logo. To me it looks like a fit, however, not easy to quantify ;)

**Comment by eguiraud** [comment]
A long discussion on mattermost on this topic was concluded by this comment of Axel's, I think this is where we are at the moment:

> Here's my current reasoning - not sure how convincing it is.
>
>    - I think we need to have the flexibility to move to different links / topics.
>    - That means the old icons are out because they are a fixed set of 4.
>    - We should use a free icon set. Only then can be change topics. "Icon set" does not necessarily mean "monochrome".
>    - Picking which icon set to use is a matter of taste; voting might work.

The proposal was to gather proposals in a codimd pad and then have a vote.

**Comment by stwunsch** [comment]
My last take on a set of different icons, the example here is using the font awesome icons and adapts the colors to the ROOT logo:

![Screenshot from 2020-06-11 10-57-31](https://user-images.githubusercontent.com/6951222/84365974-8325dd00-abd2-11ea-96cd-f59c8a061067.png)

**Comment by bellenot** [comment]
I personally prefer the current "Getting Started" one...

**Comment by hageboeck** [comment]
I honestly like none of the proposed icons. I don't know if it's en vogue now, but all these fat lines seem to always shout at me.
IT'S LIKE THOSE PEOPLE WHO FOLLOW CAPTAIN CAPS AND HIS SHIFTCREW. :-)

**Comment by hageboeck** [comment]
> My personal opinion: I like the new ones way better than the old ones (why a window frame?!) even though I'd be happy to see different icons than the new ones. They are just the obvious font-awesome icons, I guess... I.e. alternative proposals?

A trusted source tells me that alternatives to font-awesome are "glyphicons" and "material design icons"

**Comment by stwunsch** [comment]
Thanks, I'll have a look what we can find there as alternatives. In the meanwhile, here another version with the old ones but a different color scheme:

![Screenshot from 2020-06-11 17-34-23](https://user-images.githubusercontent.com/6951222/84406515-ed0da900-ac09-11ea-848f-0fbdcd14bb73.png)

**Comment by stwunsch** [comment]
Another option using icons from https://material.io/resources/icons/?style=outline, and open source. Screenshot with a proposal below:

![Screenshot from 2020-06-11 18-09-44](https://user-images.githubusercontent.com/6951222/84412052-f51c1780-ac0e-11ea-8174-bcc4a1a38738.png)

**Comment by bellenot** [comment]
So I prefer the original icons and color, and not sure about the header image...

**Comment by stwunsch** [comment]
Regarding the header image, there's a separate thread here: https://github.com/root-project/web/issues/137

**Comment by eguiraud** [comment]
@stwunsch I think this can be closed?

**Comment by stwunsch** [comment]
Yep, thanks for the reminder!
