### ISSUE TITLE
New splash image

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#137]
I was looking for a better splash logo but couldn't really find the one. However, I found out the old one is a CMS event display and I found another one which is imho slightly better suited. I adapted it a little bit and gave it a try, see below.

Also I'm not sure whether we need approval from someone to use it? Same for the current one.

I think that the main issue is the black color, it just doesn't go well with the blueish rest of the website.

![Screenshot from 2020-06-09 23-57-15](https://user-images.githubusercontent.com/6951222/84205485-7e1b3d80-aaad-11ea-9857-590e0ad2ab29.png)

**Comment by stwunsch** [comment]
And here the link to the image on the right: https://www.quantumdiaries.org/tag/tau/

**Comment by Axel-Naumann** [comment]
Yes, maybe that's better. My main concern with the image is that it's not done with CMS's event display - which is based on ROOT's TEve! @osschar would you have anything comparable in your virtual drawer?

**Comment by stwunsch** [comment]
@osschar Thanks for the link! I post two snipplets from the images you sent which would serve imho as a nice splash image.

![Screenshot from 2020-06-11 08-56-33](https://user-images.githubusercontent.com/6951222/84354959-173b7880-abc2-11ea-9038-2e4c21b85434.png)
![Screenshot from 2020-06-11 08-56-25](https://user-images.githubusercontent.com/6951222/84354962-19053c00-abc2-11ea-9265-50c39359def4.png)

**Comment by stwunsch** [comment]
Here another proposal using the images form @osschar 

![Screenshot from 2020-06-11 09-42-48](https://user-images.githubusercontent.com/6951222/84359007-45bc5200-abc8-11ea-8505-c067d697a3ab.png)

**Comment by vepadulano** [comment]
> Here another proposal using the images form @osschar
> 
> ![Screenshot from 2020-06-11 09-42-48](https://user-images.githubusercontent.com/6951222/84359007-45bc5200-abc8-11ea-8505-c067d697a3ab.png)

I appreciate the image on the right for its white background and higher resolution wich make it fit better with the rest of the page. Not completely sure about the color scheme, but definitely an improvement imho

**Comment by stwunsch** [comment]
You can also have a look at the link @osschar posted, there are different color schemes available. Also I can use gimp and just map colors to adapt the scheme to whatever you like!

**Comment by sitongan** [comment]
> Here another proposal using the images form @osschar
> 
> ![Screenshot from 2020-06-11 09-42-48](https://user-images.githubusercontent.com/6951222/84359007-45bc5200-abc8-11ea-8505-c067d697a3ab.png)

Personally  I like both the new splash pic and the colour scheme. Having the background colour as a purer shade of white as opposed to off-white also feels a bit modern imo.

**Comment by hageboeck** [comment]
> Here another proposal using the images form @osschar
> 
> ![Screenshot from 2020-06-11 09-42-48](https://user-images.githubusercontent.com/6951222/84359007-45bc5200-abc8-11ea-8505-c067d697a3ab.png)

I actually like the dark background. This seems to be the standard for most event displays. Whether you want to make the background white or not, I'm slightly leaning towards not white, but indifferent enough that I won't complain.

**Comment by osschar** [comment]
Looking at what you've taken, here two more (at different resolutions):
http://xrd-cache-1.t2.ucsd.edu/matevz/Tprime-200pu-PhaseII-for-ROOT/

Axel asked for fewer tracks and jets.

**Comment by stwunsch** [comment]
@osschar Do you have the same images but without the endcaps? They are not looking very nice in the banner image.

**Comment by osschar** [comment]
Yes, sure .. will do it. I guess you don't need the huge resolution versions, right?

Any preference on track / calo-tower colors? I'll experiment a little ...

**Comment by Axel-Naumann** [comment]
Thank you, Matevz! ROOT's blue and cyan would of course be fantastic, possibly with an orange/yellow and / or light gray?

**Comment by osschar** [comment]
Sure, it's a pleasure, no worries, as long as you don't mind me taking two days for every iteration ;)

What do you mean by ROOT's blue & cyan? Can you give me rgb values or tell me where to color-pick them off from? :)

**Comment by Axel-Naumann** [comment]
Here you go! They just come out of ROOT's logos:

https://root.cern.ch/img/logos/ROOT_Logo/misc/logo_full-plus-text-hor.png
![blue with text](https://root.cern.ch/img/logos/ROOT_Logo/misc/logo_full-plus-text-hor.png)

https://root.cern.ch/img/logos/ROOT_Logo/misc/generic-logo-cyan-512.png
![cyan logo](https://root.cern.ch/img/logos/ROOT_Logo/misc/generic-logo-cyan-512.png)

RGB values:
![#20619B](https://via.placeholder.com/150/326197/000?text=20619B)
![#00D7E8](https://via.placeholder.com/150/00D7E8/000?text=00D7E8)

**Comment by stwunsch** [comment]
@osschar That sounds great! I'm sure that gives the website a professional look :) Thanks in advance! Regarding the resolution, I guess around 2000x2000 is absolutely fine (including some cropping afterwards) to be on the safe side, that refers to the "large" version from your link.

**Comment by osschar** [comment]
Alrighty, round 2 :)
https://desire.physics.ucsd.edu/matevz/Tprime-200pu-PhaseII-2018-08-for-ROOT-2/

**Comment by stwunsch** [comment]
These are great! :)

**Comment by eguiraud** [comment]
I think this can be closed! https://ph-root-2.cern.ch/
