### ISSUE TITLE
Use clean ROOT logo and adapt splash logo color

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#138]
Another proposal using the clean ROOT logo and an adapted splash image. IMHO the best version so far giving a clean look.

What do you think?

![Screenshot from 2020-06-10 00-20-33](https://user-images.githubusercontent.com/6951222/84206936-7e690800-aab0-11ea-91c6-87821e05e8ef.png)

**Comment by couet** [comment]
Which one is the best is really a matter of taste...  I prefer le left one.

**Comment by Axel-Naumann** [comment]
@stwunsch is this still relevant?

**Comment by stwunsch** [comment]
Let's close!
