### ISSUE TITLE
Line height inconsistent for Latest Releases / Tech Blog

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#141]
Both enumerate titles, but whereas the "Latest Releases" line height is about 1.5, that for the blog is 1.

"Latest Releases" uses a `<ul><li>` while "Tech Blog" does not. That should be consistent.

**Comment by Axel-Naumann** [comment]
Alternatively we could also use `<ul><li>` for the "Tech Blog" list.

**Comment by stwunsch** [comment]
Fixed by #217
