### ISSUE TITLE
Mirror the splash image

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#143]
"ROOT - a modular scientific software toolkit" is written on jet sprays. Mirroring the image along the vertical would have it written on black.

**Comment by couet** [comment]
Done

**Comment by stwunsch** [comment]
Probably we could also shift the detector image to the right? Potentially this looks better. Though then you would still keep it the other way around, so not mirrored, to let the "spray" come from the right.

**Comment by couet** [comment]
At least now the text appears on the black part. 
Feel free to modify the image the way you think is the best.

**Comment by Axel-Naumann** [comment]
Looks like that's superseded by #137
