### ISSUE TITLE
target: _blank in navbar does not open links in new tabs

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#166]
I suppose the purpose of lines such as this:

https://github.com/root-project/web/blob/bbfdc86579b3b9af8ea1f39e115be5a07f68f9ae/_data/navigation.yml#L118

is to have external links in the navbar open new browser tabs, but it does not work for me on firefox.

**Comment by couet** [comment]
You are right, it does not seems to work. Same issue on Safari.

**Comment by couet** [comment]
Actually the code implementing the target attribute was in nav_list and masthead.html and has been lost.
https://github.com/root-project/web/commit/5494528cd8e0ecb59f45917a2ccf1e5044719740
