### ISSUE TITLE
"ROOT is ..." section should be updated.

### ISSUE THREAD

**Issue by hageboeck** [root-project/web#169]
It's too short, and it should be clarified that it has been developed in HEP.

**Comment by eguiraud** [comment]
see also discussion here about linking from "ROOT is..." to the about section: https://github.com/root-project/web/issues/65

**Comment by eguiraud** [comment]
might be fixed by #238

**Comment by Axel-Naumann** [comment]
Oops, I agree that's fixing it but that wasn't intentional :-)

**Comment by Axel-Naumann** [comment]
https://github.com/root-project/web/pull/238 is merged
