### ISSUE TITLE
"Tutorials" or "code examples": must pick one

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#17]
https://root.s3-website.cern.ch/web/manual refers to "Tutorials", while https://root.s3-website.cern.ch/web/get_started calls them "Code examples". We should be consistent.

**Comment by Axel-Naumann** [comment]
+1 for "tutorials"!

**Comment by eguiraud** [comment]
There seems to be convergence towards "tutorials". @JohannesHentrich would it be ok if I changed "code examples" to "tutorials" through the website?

**Comment by couet** [comment]
fixed by https://github.com/root-project/web/pull/369
