### ISSUE TITLE
Reference latest “pro” release ...

### ISSUE THREAD

**Issue by couet** [root-project/web#19]
Reference latest “pro” release for all reference guide links

**Comment by Axel-Naumann** [comment]
I think linking everything to master - given we have addressed #102 - will is just better: it shows everything master has to offer, while still giving access to other versions quickly.

@couet and I verified that all doxygen links point to master. And then there's #103

**Comment by eguiraud** [comment]
but virtually nobody is looking for master?

if you go with this I'd suggest you make it quite visible, when the user lands on the reference page, that it is for an unreleased version

**Comment by Axel-Naumann** [comment]
It's shown in the version selection. I think it's in our interest to make master's features visible.
