### ISSUE TITLE
No option to see old blog posts

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#193]
I cannot find an option to see the old blog posts. Did I miss it?

**Comment by stwunsch** [comment]
I've just realized that we have the overview in the news section: https://ph-root-2.cern.ch/news

**Comment by stwunsch** [comment]
Though we should link more directly there, it's not obvious.

**Comment by stwunsch** [comment]
A propsal is here: https://github.com/root-project/web/pull/217

And here a screenshot of the new appearance (left) and the current state (right):

![Screenshot from 2020-06-18 15-31-23](https://user-images.githubusercontent.com/6951222/85027092-cd323400-b179-11ea-8cfb-fcf535f40cb1.png)

**Comment by stwunsch** [comment]
The text shown for each blog post of the "Under the Spotlight" is the first paragraph of the post. The div is not responsive enough to spread the 3 posts according to the right hand side :/

**Comment by stwunsch** [comment]
Second option here, this one does not use a list for the tech blog entries and has therefore less spacing: https://github.com/root-project/web/pull/218

Screenshot below (left: new, right: old)

![Screenshot from 2020-06-18 15-42-26](https://user-images.githubusercontent.com/6951222/85027946-c952e180-b17a-11ea-8275-d84ea67463e3.png)

**Comment by Axel-Naumann** [comment]
I prefer the first option due to https://github.com/root-project/web/issues/141 - consistent line heights.

**Comment by stwunsch** [comment]
@couet What's your opinion?

**Comment by couet** [comment]
I have no real preference.

**Comment by stwunsch** [comment]
So we'll go with #141!
