### ISSUE TITLE
Attribution for front page icons

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#197]
The licensing terms can be found at the bottom of https://linearicons.com/free

**Comment by stwunsch** [comment]
@Axel-Naumann @eguiraud Any good idea where to put this? If you can provide input for that, I woudl put something in.

**Comment by stwunsch** [comment]
Good idea to put it there, I gave it a try here: https://github.com/root-project/web/pull/230

Would be good to go, though the page does not show up on the left navigation thingy :/ I couldn't figure out why.

**Comment by eguiraud** [comment]
You need to add it in `_data/navigation.yml`

**Comment by stwunsch** [comment]
Ah thanks! I've put it in. @Axel-Naumann Up to you to review!
