### ISSUE TITLE
Provide custom 404 page

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#199]
It's currently the default Apache
```
Not Found

The requested URL was not found on this server.
Apache/2.4.18 (Ubuntu) Server at ph-root-2.cern.ch Port 443
```

**Comment by eguiraud** [comment]
we could have a contest on the forum for the funniest ROOT-related 404 page

**Comment by eguiraud** [comment]
why assigned to me?

**Comment by couet** [comment]
I was not sure. You seems to have ideas about it. It was unassigned. You can de-assign or assign it to somebody else.

**Comment by couet** [comment]
The 404 page is not in place
