### ISSUE TITLE
Use recommended way to specify relative URLs

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#208]
We should use the URL filters provided by Jekyll to fix potential issues with relative link:

```html
<!-- For styles with static names... -->
<link href="{{ 'assets/css/style.css' | relative_url }}" rel="stylesheet">
<!-- For documents/pages whose URLs can change... -->
[{{ page.title }}]("{{ page.url | relative_url }}")
```

See https://jekyllrb.com/docs/github-pages/#project-page-url-structure and https://github.com/github/pages-gem/issues/460

**Comment by eguiraud** [comment]
#227 fixed remaining non-relative URLs. I'm pretty sure all links are ok, because we deploy PRs with a baseurl and the main website without and HTML proofer is green in both cases. I think this can be closed.
