### ISSUE TITLE
Enable checks of links protected by SSO page

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#214]
See the workflow of the HTML proofer, which ignores links to grafana and jenkins

**Comment by eguiraud** [comment]
Is it at all possible to have HTML proofer not error out when it encounters SSO-protected pages?

**Comment by stwunsch** [comment]
Doesn't the SSO show only up if the URL exists? You can compare https://foobnch-grafana-test.cern.ch/ against https://foobnch-grafana-test.cern.ch/. In principle, it seems doable though not with the htmlproofer we use, I guess.
