### ISSUE TITLE
Remove "GitHub Pages" section from "Editing the ROOT web site"

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#222]
Since we don't have `/web` anymore (and since people can and should just run `jekyll` locally) we should remove the points 4. to the end of /for_developers/web#get-the-root-web-site-sources

**Comment by eguiraud** [comment]
Should mention instead that (for collaborators with permissions) PRs from branches that are in this repo are automatically deployed.

**Comment by eguiraud** [comment]
I think the titular issue is fixed. @couet where would it be appropriate to mention that PRs from branches in the upstream repo are automatically deployed at `root.cern/<prnumber>`?

**Comment by couet** [comment]
@eguiraud : I think it is mentioned here: http://127.0.0.1:4000/base/for_developers/web/#get-modifications-upstream
Seems to me this issue can be closed.

**Comment by eguiraud** [comment]
Yes, @hageboeck added that paragraph in #337 . This can be closed.
