### ISSUE TITLE
No prompt shown in /about/interactive_or_built_applications/

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#225]
When we introduce interactivity we should be showing what it looks like: show a prompt!

**Comment by couet** [comment]
Done

**Comment by Axel-Naumann** [comment]
Let me be more explicit:
```
root [0] int i = 7
(int) 7
root [1] ++i
(int) 8
```
would be a minimal showcase for the prompt. This was not meant to ask for `root[0]` on a black background :-)
