### ISSUE TITLE
Protect main branch

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#231]
Since ~~gh-pages~~ main is our deployed website (due to the CI), we should protect the branch and allow only PRs

**Comment by eguiraud** [comment]
It's probably time to make a decision :smile: I'm in favor, I don't see any reason why it should be possible to push to production directly without passing through a pull reqeust.

**Comment by Axel-Naumann** [comment]
We will do that after the publication:
The release page generation (in Jenkins) currently requires pushing to the branch without a PR; I prefer to improve that as a second step, after the page is published, because I need to synchronize publication of v6.22/00 and the web page.

**Comment by Axel-Naumann** [comment]
I know how to require a review before merging - but I don't know how to require just a PR. Anyone?

**Comment by eguiraud** [comment]
Uhm if I understand correctly, we can only push directly to `main` because we are administrators, and we can bypass the "require all checks to pass before merging" rule. If we ticked the "include administrators" checkbox, then no one could push directly to `main`. The downside, however, is that no one could override red checks anymore.

There does not seem to be a way to prevent direct pushes while still allowing to override red PR checks.

**Comment by Axel-Naumann** [comment]
So, @eguiraud - what do you recommend to do? Is the current setting ("Require status checks to pass before merging ") good enough and this can be closed? If not, please let me know which exact GitHub branch protection setting you'd like to see changed.

**Comment by eguiraud** [comment]
as far as I understand, options are:
- protect `main` from pushes but also prevent PR merges unless everything is green
- allow PRs to be merged even if checks are red, but let admins push directly to `main`

I don't have a strong preference...we could leave things as they are as long as we agree between ourselves that we should stick to PRs

**Comment by Axel-Naumann** [comment]
> protect main from pushes but also prevent PR merges unless everything is green

That's what we have today. AFAIK admins can always push.

Good enough?

**Comment by Axel-Naumann** [comment]
Let me know if we can do something better and I reopen!
