### ISSUE TITLE
Front page uses too many different fonts

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#24]
![image](https://user-images.githubusercontent.com/10999034/83655000-24eb6f80-a5be-11ea-8875-9bc1c0976410.png)

![image](https://user-images.githubusercontent.com/10999034/83655027-2fa60480-a5be-11ea-9429-e26f8f630bbb.png)

![image](https://user-images.githubusercontent.com/10999034/83655050-3765a900-a5be-11ea-8bc2-f411e17b5223.png)

![image](https://user-images.githubusercontent.com/10999034/83655093-44829800-a5be-11ea-9e83-8163f39eef96.png)

![image](https://user-images.githubusercontent.com/10999034/83655212-6d0a9200-a5be-11ea-9929-fef1d2ef01f0.png)

**Comment by couet** [comment]
Is there a rule on the number of fonts to be use on a web site Front page ? does it exists some where ? Some guidelines might be useful ... I never had any course on that.

**Comment by eguiraud** [comment]
There are no hard and fast rules (it's design after all), but see e.g. https://engageinteractive.co.uk/blog/how-many-fonts-is-too-many-fonts

**Comment by couet** [comment]
Thanks !

**Comment by couet** [comment]
I have changed the font for the text under the Icon. That's the only place where the font was changed for the ROOT web site. For the rest the "minimal mistakes" theme uses the system fonts as said here: https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#font-stacks

**Comment by Axel-Naumann** [comment]
Fixed, but #10 will re-introduce a new one ;-)
