### ISSUE TITLE
Set style's `site.footer.links` instead of modifying style's _includes/footer.html

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#246]
Less modifications of `minimal_mistakes` is better, esp as there is a way to set these icons.

**Comment by stwunsch** [comment]
We have already outsourced the footer from the theme repo to `web`, see `_includes/footer/custom.html`.

Do you mean that we want to use the footer served by the theme (see [here](https://mmistakes.github.io/minimal-mistakes/)) and just replace the icons?

What about the CERN logo and "disclaimer"? Do we want to keep them?

**Comment by Axel-Naumann** [comment]
We have mods in the theme's footer that can be easily handled in web.git instead; see https://github.com/root-project/minimal-mistakes/commit/d2dcbb974fad06c1f0b4ad2f5168c7953ed19fc6#diff-7693eb643e8fe8b8d46b407909b408ce

**Comment by couet** [comment]
This ia now fixed. All the ROOt web site footer stuff is now in root-project/web
