### ISSUE TITLE
Frontpage download link should be "automatic"

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#255]
Given the "latest" release concept we will introduce, the download link on the splash should link there, automatically. It's currently hard-coded to point to 6.20/04.

**Comment by eguiraud** [comment]
I would also suggest to use "latest release" everywhere and drop the quirky "PRO" and "OLD" that nobody apart from ROOT uses

**Comment by Axel-Naumann** [comment]
That's independent and https://github.com/root-project/web/issues/112

**Comment by couet** [comment]
To implement that I would require first to have this PR in:
https://github.com/root-project/web/pull/260 (pro/old -> latest)

**Comment by couet** [comment]
These two PRs implement this:
https://github.com/root-project/web/pull/268
https://github.com/root-project/minimal-mistakes/pull/11

**Comment by Axel-Naumann** [comment]
Fixed, thanks!
