### ISSUE TITLE
Create more responsive front page

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#257]
1. Could we have a more responsive layout if we would move the spotlight/blog/release sections into divs?

![Screenshot from 2020-06-22 18-32-18](https://user-images.githubusercontent.com/6951222/85312294-f1ae4900-b4b6-11ea-96fe-a99d5043a49c.png)

2. The subtitles of the icons are misaligned on mobile devices

![Screenshot from 2020-06-22 18-32-00](https://user-images.githubusercontent.com/6951222/85312299-f2df7600-b4b6-11ea-93f8-ce6229123b1e.png)

3. The header shows a lonel "About", but should probably just all vanish into the sandwich button.

![Screenshot from 2020-06-22 18-32-11](https://user-images.githubusercontent.com/6951222/85312297-f246df80-b4b6-11ea-935f-056d4680655f.png)

**Comment by eguiraud** [comment]
about 2, I must say the layout tries hard to keep them aligned (you can check by resizing the browser window on your computer), i.e. the situation is much better than in #26 . At some point the row won't fit the screen width, and something has got to give

**Comment by stwunsch** [comment]
True, however, I think on most mobile devices they are misaligned which is a pitty.
