### ISSUE TITLE
Link titles in front page appear misaligned on mobile

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#26]
![image](https://user-images.githubusercontent.com/10999034/83655593-e5715300-a5be-11ea-9b0a-3b803afe4cd3.png)

**Comment by Axel-Naumann** [comment]
Depends on #136

**Comment by stwunsch** [comment]
Should be fixed by https://github.com/root-project/web/pull/223

**Comment by Axel-Naumann** [comment]
#223 is merged.
