### ISSUE TITLE
Font colors on the front page are not consistent

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#261]
https://github.com/root-project/web/pull/256 is one step in the right direction, but the headers are also full black and the blue of the font in the blog section does not seem to match the 'root blue' of the rest.

**Comment by Axel-Naumann** [comment]
Link colors fixed in https://github.com/root-project/minimal-mistakes/commit/a682cf91c0846ef8304e08cd01bf88be20a842c7

https://github.com/root-project/web/pull/294 for box titles.
