### ISSUE TITLE
Do not enclose front page icons in a border when hovering over them

### ISSUE THREAD

**Issue by etejedor** [root-project/web#279]
From Diogo: "the icons are not in a square, so putting the hover as a square doesn't look good. If they really want the hover effect, then they can make it larger and around the icon and the text"

**Comment by etejedor** [comment]
![image](https://user-images.githubusercontent.com/8089558/85578654-868d7f80-b63a-11ea-9eb9-93e06da201f3.png)

Example of the suggestion from Diogo.

**Comment by eguiraud** [comment]
@stwunsch the original PR was closed when we switched from `gh-pages` to `main`. However if I understood the PR correctly, it was removing the borders rather than expanding them to also enclose the text. Not sure how we want to proceed?
