### ISSUE TITLE
Change underline color and width when hovering over the sections in the upper bar

### ISSUE THREAD

**Issue by etejedor** [root-project/web#280]
From @diocas: "it would look better if the underline was white, with more spacing bellow the text and even with a different animation, and maybe a bit thiner than now"

**Comment by couet** [comment]
this PR makes the underline white
https://github.com/root-project/minimal-mistakes/pull/13

**Comment by Axel-Naumann** [comment]
@couet you prefer to keep thickness and position unchanged?

**Comment by couet** [comment]
No but i did not managed to change them ....

**Comment by Axel-Naumann** [comment]
I can probably help :-)

**Comment by Axel-Naumann** [comment]
I can tell you that the CSS entry which does the white underline is this one:
```css
.greedy-nav a:hover::before {
  background-color: white;
```
```css
.greedy-nav .visible-links a::before {
  height: 4px;
```
defines the width of the line; setting this to 1px would IMO address this issue well enough.

**Comment by couet** [comment]
I did not find a solution ... I will look at what Axel suggests.

**Comment by couet** [comment]
Fixed by: https://github.com/root-project/minimal-mistakes/pull/20
Thanks Axel :-)
