### ISSUE TITLE
Logo and background use different colors

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#287]
Those should be the same blue. That's with Firefox mobile.

![Screenshot_20200626-073037_Firefox_1.jpg](https://user-images.githubusercontent.com/144675/85824322-d164df80-b77f-11ea-8a19-2f1f3d707029.jpg)

**Comment by couet** [comment]
I tried it with firefox mobile on an iPhone and I do not see this problem. The blue is the same.

**Comment by Axel-Naumann** [comment]
OK, let's assume it's a Firefox android issue...
