### ISSUE TITLE
Set up url forwarding for most visited Drupal pages

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#288]

**Comment by Axel-Naumann** [comment]
What matters are the entry pages. Here, Nov 2019 and May 2020 as examples:
![Image Pasted at 2020-6-26 09-58](https://user-images.githubusercontent.com/144675/85834653-0e3ad180-b794-11ea-8f56-37c5fd3dd96e.png)
![Image Pasted at 2020-6-26 09-56](https://user-images.githubusercontent.com/144675/85834669-1135c200-b794-11ea-8472-82130d2c5e8b.png)

**Comment by Axel-Naumann** [comment]
I also looked at Feb 2020. The list is thus (>= 10 entries / month):

| old | new |
|-----|-----|
| [/blog](https://root.cern/d/blog) | |
| [/blog/257](https://root.cern/d/blog/257) | |
| [/blog/rootrwhy](https://root.cern/d/blog/rootrwhy) | |
| [/blog/spin-little-disk-spin](https://root.cern/d/blog/spin-little-disk-spin) | |
| [/blog/root6-and-backward-compatibility](https://root.cern/d/blog/root6-and-backward-compatibility) | |
| [/root-version-v5-34-00-patch-release-notes](https://root.cern/d/root-version-v5-34-00-patch-release-notes) | |
| [/rainbow-color-map](https://root.cern/d/rainbow-color-map) | |
| [/howtos](https://root.cern/d/howtos) | |
| [/how/how-find-peaks-histograms](https://root.cern/d/how-find-peaks-histograms) | |
| [/gallery](https://root.cern/d/gallery) | |
| [/coding-conventions](https://root.cern/d/coding-conventions) | |
| [/installing-xrootd](https://root.cern/d/installing-xrootd) | |
| [/building-root](https://root.cern/d/building-root) | |
| [/mathmore-library](https://root.cern/d/mathmore-library) | |
| [/content/release-61600](https://root.cern/d/content/release-61600) | |
| [/content/release-62000](https://root.cern/d/content/release-62000) | |
| [/content/release-61802](https://root.cern/d/content/release-61802) | |
| [/content/release-61902](https://root.cern/d/content/release-61902) | |
| [/downloading-root](https://root.cern/d/downloading-root) | |
| [/root-users-workshop-2018](https://root.cern/d/root-users-workshop-2018) | |
| [/courses](https://root.cern/d/courses) | |
| [/selecting-dictionary-entries-linkdefh](https://root.cern/d/selecting-dictionary-entries-linkdefh) | |
| [/team](https://root.cern/d/team) | |
| [/roottalk-digest](https://root.cern/d/roottalk-digest) | |
| [/meetings](https://root.cern/d/meetings) | |
| [/about-root](https://root.cern/d/about-root) | |
| [/releases](https://root.cern/d/releases) | |
| [/guides/reference-guide](https://root.cern/d/guides/reference-guide) | |
| [/development](https://root.cern/d/development) | |
| [/root-user-guides-and-manuals](https://root.cern/d/root-user-guides-and-manuals) | |
| [/documentation](https://root.cern/d/documentation) | |
| [/faq/can-i-integrate-root-my-cmake-build](https://root.cern/d/faq/can-i-integrate-root-my-cmake-build) | |
| [/news](https://root.cern/d/news) | |
| [/root-7](https://root.cern/d/root-7) | |

**Comment by couet** [comment]
```
/howtos -> https://root-forum.cern.ch/c/howto/
/coding-conventions -> /contribute/coding_conventions/ 
/mathmore-library -> /manual/math/#mathmore-library
/selecting-dictionary-entries-linkdefh : this drupal book has not been translated.
/meetings -> for_developers/meetings/
for_developers/meetings/ : I do not see an equivalent

```

**Comment by Axel-Naumann** [comment]
Done, mostly:

For now, `/roottalk-digest` and `/selecting-dictionary-entries-linkdefh` forward to their `/d/` snapshots; that should get fixed later.

**Comment by Axel-Naumann** [comment]
Replacing `/d/` is now #308 - we can close this.
