### ISSUE TITLE
Ending slash needed ....

### ISSUE THREAD

**Issue by couet** [root-project/web#29]
With following URL (no ending slash) the jsroot images are not displayed:
https://root.s3-website.cern.ch/web/manual/graphics

One needs the URL:
https://root.s3-website.cern.ch/web/manual/graphics/

The ending slash is automatically added with the Github I/O of the web site but not with the S3 one... why ?

https://root-project.github.io/web/manual/graphics/

**Comment by Axel-Naumann** [comment]
I will add forwarding to the backup root.cern so we can try.

**Comment by Axel-Naumann** [comment]
Fixed by https://github.com/root-project/web/pull/245
