### ISSUE TITLE
Add big red banner in ref guide for versions other than latest (including master)

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#303]
On the forum, users complain that their ROOT does not do what the reference says it does all the time. Please please add a big orange banner that says "you are looking at the documentation for ROOT master branch. To switch to the documentation for your version, use the button below".

_Originally posted by @eguiraud in https://github.com/root-project/web/issues/102#issuecomment-648724103_

**Comment by Axel-Naumann** [comment]
What if people are looking at any other version X while they have version Y? Master is now more exposed, but we should still count on people learning to read version numbers... I'm also not a big fan of adding preemptive "caution coffee is hot" signs :-) Such a banner adds noise for everyone, to the benefit of few that will likely also post "doesn't work!" *with* a red banner...

**Comment by eguiraud** [comment]
Ok what about a _small_ red banner? :smile:

I think the core of the matter is that user expectation is that when we link at the reference guide we are linking to documentation for the latest stable release. That's how most projects do it, see e.g. https://pytorch.org, https://www.djangoproject.com, https://boostorg.github.io/hana, https://doc.qt.io/qt-5/reference-overview.html .
Given that we do this quirky thing that we link to docs that will have features that users won't be able to use, I think it's nice to warn them.

Feel free to close this if I failed to convince you.
