### ISSUE TITLE
The "install" button should go to the /install section, not to the release page

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#306]
Our current release pages have several issues (#124, #68, #66, #62), but more than anything, I don't think they are a good place to find information on how to install ROOT -- and they shouldn't be, we have /install for that. In fact the behavior of the button must have changed at some point, because a few  weeks ago that button pointed to the /download section, not to a release page.

As a non-expert user: I land on root.cern, click the big "Install v6.20/04" button, and end up at https://root.cern/releases/release-62004 which only lists _some_ of the ways in which ROOT can be installed, and with little to no explanation.

What do you think? Can we change where the button points to?

**Comment by couet** [comment]
yes surely. let me check

**Comment by couet** [comment]
The change was done by the PR from Axel:
https://github.com/root-project/web/commit/fafd6ae476bbff525bceea7604d0e9e8a3ce262e
The last PR I did was to autosize the link but the "Install V..." button point to the link Axel defined.

**Comment by eguiraud** [comment]
Alright but my point really wasn't to ask who changed it :smile: What's your opinion?

**Comment by Axel-Naumann** [comment]
We need install info *for a specific version*. I'm perfectly ok to have that button link to `/install`, but then `/install` needs links to `{{%latest}}` so to say, in docker etc. We need to make it easy for people to upgrade to the latest ROOT version.

**Comment by eguiraud** [comment]
> We need install info for a specific version.

> We need to make it easy for people to upgrade to the latest ROOT version.

I totally agree, the problem is that the release pages do not contain useful install info. Besides the issues already listed above:

* they do not list several of the available installation options
* they fail to mention the need to install pre-requisites for the installation methods mentioned
* I don't think the suggested setup command `. /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.22.00/x86_64-centos7-gcc48-opt/bin/thisroot.sh` works on systems other than lxplus because dependencies might be missing?
* it shows the source distribution first, and does not explain how to use either that or the binary distribution. For the non-expert user, it's not clear which one is better for them

> /install needs links to {{%latest}}

It does, at the top of the page. Automatically using `{{%latest}}` in the installation instructions is not always easy (because sometimes you need `6.22.02`, sometimes `v6-22-00`, sometimes `LCG_98`), so instead I put comments such as `#substitute `v6-20-00-patches` with the patches branch of the latest release` in the example commands. I realize this can be improved, I'll take care of it.

**Comment by eguiraud** [comment]
Hi,
I'd like to revive the conversation here: the binary release pages are very confusing for a non-expert user (see all the issues mentioned above) and should not be what users see when they press the nice big friendly "install v6.22/02" button on the front page.
