### ISSUE TITLE
Link checker refuses relative links to non-jekyll pages of root.cern

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#310]
Linking to `/doc/master` will be signaled as a broken link; it has to be `https://root.cern/doc/master`. That's too bad :-(

**Comment by eguiraud** [comment]
I'm pretty sure that is a broken link in presence of a baseurl (e.g. when deploying PR builds), so the tool is right to point it out

**Comment by eguiraud** [comment]
Ah no, sorry, different issue... the local build the link checker checks simply cannot know that `/doc/master` will exist -- nevermind my comment.
