### ISSUE TITLE
Several useful links now unavailable on the new website

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#320]
Coming [from the forum](https://root-forum.cern.ch/t/many-documentation-and-faq-links-are-broken-on-root-cern-ch/40290), e.g.:

* https://root.cern/configuring-xproofd-or-proof-plugin-xrootd/ 
* https://root.cern/roofit/ 
* https://root.cern/cms-γ-mva-discrimination/
* https://root.cern/proof/
* https://root.cern/starting-proof/
* https://root.cern/faq/

Maybe we can resurrect some of these, or make them point to corresponding resources in the new website, or have an auto-fallback to https://root.cern/d/ when a page is not found on the new website.

**Comment by Axel-Naumann** [comment]
We need a server rewrite for URLs that have a replacement in Jekyll. We should not point to `/d/` - that's "temporary", we should remove it at some point.

**Comment by eguiraud** [comment]
Closing as we have lived for 3 years without those links.
