### ISSUE TITLE
Nightlies link doesn't work, any more.

### ISSUE THREAD

**Issue by hageboeck** [root-project/web#325]
I used to give out the link to the nightlies in the forum as
https://root.cern/nightlies

Now, it's root.cern/install/nightlies. The old one just gets you a 404, but search engines still suggest it:
![image](https://user-images.githubusercontent.com/16205615/87128866-ae165600-c290-11ea-96d5-f2b1958d1aab.png)

Maybe a redirection is in order.

**Comment by Axel-Naumann** [comment]
The server now forwards to https://root.cern/install/nightlies/
