### ISSUE TITLE
Broken link in 6.22 release notes

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#331]
Reported here: https://root-forum.cern.ch/t/dead-link-in-root-version-6-22-release-notes/40194

The link is the "here" word at the top of [this page](https://root.cern/doc/v622/release-notes.html#core-libraries). The problem is that the markdown uses a relative link to another file in the ROOT repo, but when published on the website the notes are not inside the repo.

EDIT: the correct location is https://github.com/root-project/root/blob/v6-22-00-patches/README/README.CXXMODULES.md

**Comment by couet** [comment]
Fixed by:

https://github.com/root-project/root/pull/6069
and
https://github.com/root-project/web/pull/345
