### ISSUE TITLE
Status of the "Picking up an Idea" section

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#35]
See [here](https://root-project.github.io/web/contribute/#picking-up-an-idea), the section **Picking up an Idea** does not seem to be actively maintained.

Should we remove the section in favor of a cleaner message of the page?

**Comment by Axel-Naumann** [comment]
IMO we must update or remove it before we release.

**Comment by couet** [comment]
Is an update possible ? do we have a "list of ideas" elsewhere ?
If not I guess we should remove this completely.

**Comment by Axel-Naumann** [comment]
I'll check.

**Comment by Axel-Naumann** [comment]
https://github.com/root-project/web/pull/286

**Comment by couet** [comment]
This issue is solved. I close it.
