### ISSUE TITLE
Footer icon valign, padding

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#354]
After #351 / #109 I now see vertically "misaligned" text and icons:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/144675/88788240-58e5aa00-d195-11ea-834a-eb39a2b3bf76.png">

It might also be nice to increase the distance between "Forum" and the bug icon, and "(JIRA)" and the mail icon, to visually separate the three elements "forum", "bug", "mail"

**Comment by couet** [comment]
The footer has been completely redesigned.
