### ISSUE TITLE
Add Fermilab logo

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#356]
We've got an OK to add just the "logomark" from https://www.fnal.gov/faw/designstandards/logo.html to the ROOT website. It should be placed next to the CERN logo, likely to the CERN logo left, FNAL right.

**Comment by Axel-Naumann** [comment]
And Princeton. They require the logo and the logo-text to be shown. 
![PU-standard](https://user-images.githubusercontent.com/144675/88808097-bcca9b80-d1b2-11ea-9e8c-9077240bc930.png)

**Comment by couet** [comment]
Done
