### ISSUE TITLE
Put "Under the Spotlight" under the spotlight

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#362]
Usecase: casual reader that ends up on the website for some blog-unrelated reason (because virtually nobody will check our website just to see if we posted something on the blog)

Problem: blog post titles are currently so small that they don't catch the eye of the reader at all.

A first attempt to fix this issue that did not make the cut can be found at #357 .

By Axel:

> I agree that's an issue. What about this:
> - we merge tech blog and "under the spotlight" - as a use, why do I care about these two being separate? What makes something show up in one instead of the other?
> - we remove the header "Under the Spotlight"
> - the "under the spotlight" entry titles are sized to match the current "Under the Spotlight" header.

_Originally posted by @Axel-Naumann in https://github.com/root-project/web/pull/357#issuecomment-665669186_

By Olivier:

> The separation between "spotlight" and "tech blog" came from the old web site. I think "spotlight" was for the more recent posts ... that's it ... I agree they can be merged.

**Comment by couet** [comment]
I think this in fixed (changed) now. I guess we can close this one ?

**Comment by eguiraud** [comment]
The titular problem, that blog post titles don't catch the eye of the reader, is still present.
Axel's suggestion to fix the styling was to remove the header and to increase the font size of the blog titles.

**Comment by couet** [comment]
ok .... i will do that

**Comment by couet** [comment]
PR here: https://github.com/root-project/web/pull/376

**Comment by Axel-Naumann** [comment]
@eguiraud do you agree that this is now addressed?

**Comment by eguiraud** [comment]
yes!
