### ISSUE TITLE
Add `hadd` to manual

### ISSUE THREAD

**Issue by vepadulano** [root-project/web#370]
The `hadd` command (and possibly others in `$ROOTSYS/bin`) should have their place in the manual. Right now the only way I could find to get information about them is manually tiping `man hadd` in a terminal and that doesn't really show a lot of meta-information (such as the default max tree size). 
While maybe `hadd` is widespread enough, it is possible that `rootls` or `rootcp` are not even known by some users so they would also benefit from some visibility on the website.

What do we think of this? And what would be the best way to add this information without dispersion and duplication?

**Comment by couet** [comment]
To avoid duplication such web pages should be generated automatically together with the man pages (ideally).

**Comment by couet** [comment]
Here it is https://root.cern/manual/storing_root_objects/#merging-root-files-with-hadd
And also here : https://root.cern/manual/storing_root_objects/#root-command-line-tools
