### ISSUE TITLE
RSS/Atom feed does not include release announcements

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#386]
Our feed: https://root.cern/feed.xml .

Also see the discussion at https://sft.its.cern.ch/jira/browse/ROOT-10949 .

**Comment by couet** [comment]
this PR should fix it: https://github.com/root-project/web/pull/402

**Comment by couet** [comment]
This PR generates error when building site:
https://github.com/root-project/web/pull/402/checks?check_run_id=1065998142

because of the filter: "Only allow links to ref guide for master (except in release notes)" .. is it is new one ?

**Comment by couet** [comment]
and also this one: https://github.com/root-project/web/pull/404
