### ISSUE TITLE
New download page does not call out Ubuntu

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#39]
https://root-project.github.io/web/install/

We mention Fedora, Arch, Gentoo - but not Ubuntu. We should, calling out "sorry, no apt repo, use this instead". That's much simpler than not finding the first step to take because it's not obvious.

**Comment by eguiraud** [comment]
We mention Fedora, Arch and Gentoo under "Install via a package manager". Searching the page for Ubuntu, gets you the two methods you can use to get ROOT on Ubuntu.

When we have a .deb package, we could have a "Debian and Ubuntu" section that suggests `wget url/of/root.deb && apt install root.deb` as installation method, would that clear this for you?

I don't think it makes sense to add an "Ubuntu" section under "Install via a package manager" just to say "sorry there is nothing here, see 'Download a binary release'".

**Comment by eguiraud** [comment]
@Axel-Naumann what's your take?

**Comment by Axel-Naumann** [comment]
I would still claim that it's useful. The other distros are listed, not mentioning Ubuntu looks like a big. We can now started "it's in the works, we will keep you posted" - that's still way better than not mentioning Ubuntu at all in the packages.

What adds to the weight of this is the TOC, which very visibly shows the distro names - but Ubuntu.
