### ISSUE TITLE
Usage of a consistent color palette

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#4]
I would propose to use a consistent color palette for the website, the best would be using the colors from the logo to create a "corporate style" feeling.

What do people think?

Here the current state, as reference:

![screenshot_20-04-20_12-22-17](https://user-images.githubusercontent.com/6951222/79741491-a1bdd500-8301-11ea-9280-d277c6d234db.png)

**Comment by stwunsch** [comment]
Also a matching header image would be very nice. Do we have something suitable?

**Comment by eguiraud** [comment]
what changes would you make concretely to make the palette more consistent?

**Comment by stwunsch** [comment]
I would take the colors from the logo, quite similar to what we do in the Google slides template. Here an example screenshot:

![screenshot_21-04-20_10-02-24](https://user-images.githubusercontent.com/6951222/79841129-41896a80-83b7-11ea-9966-e8c02c4d3ec4.png)

**Comment by couet** [comment]
The blue used every where (top menu bar, Icons ...) is already the ROOT-Blue coming from the logo

**Comment by Axel-Naumann** [comment]
> I would take the colors from the logo

Where is that not used? The text box with the greenish background? Maybe we can use the light cyan color from the logo?

**Comment by Axel-Naumann** [comment]
That cyan is #45d3e2 btw. #e6fdff might be a good background color that's a lighter version of it.

**Comment by stwunsch** [comment]
I would vote for using a plain white background for the website, like here on GitHub. However, I could not find the place where it is defined.

@couet Do you know?

**Comment by Axel-Naumann** [comment]
I actually le the slightly dimmed background. It's less basic, we are not a technical code management site :-)

But maybe we can compare the two and then decide?

**Comment by stwunsch** [comment]
Here a screenshot switching from the dirty background (the name of the skin ;) ) to a white one and using a blue box instead of the greenish one. Unfortunately the colors above look awkward.

![Screenshot from 2020-06-09 19-25-11](https://user-images.githubusercontent.com/6951222/84180289-92e4da80-aa87-11ea-8c1d-a2b62a215b4f.png)

**Comment by couet** [comment]
Regarding page background I do not know exactly where this colour is defined and which setting should be changed. My guess is that it should be somewhere in the forked copy of the minimal mistake theme in the root-project repository. Regarding the green colour it is simply in the index.html file of the web site. If we need to vote I prefer le left one.

**Comment by Axel-Naumann** [comment]
I was wrong with the RGB values! Correct ones:

20619B ![#20619B](https://via.placeholder.com/150/326197/000?text=20619B)
00D7E8 ![#00D7E8](https://via.placeholder.com/150/00D7E8/000?text=00D7E8)

A lighter one might thus be #dffcff 
https://via.placeholder.com/150/dffcff/000000?text=dffcff
![dffcff](https://via.placeholder.com/150/dffcff/000000?text=dffcff)

**Comment by couet** [comment]
I think we can close this one. The new web site has evolved a lot since this issues has been created.

**Comment by stwunsch** [comment]
Agreed!
