### ISSUE TITLE
Difficulties looking for help on the website

### ISSUE THREAD

**Issue by hageboeck** [root-project/web#40]
- Finding "HELP": I went on the webpage to look for help. There's nothing that's mentioning "help" on the start page.
- If I came looking for forum, it's alright, but I didn't know that Forum == Help
- Contact: There's nothing that mentions "contact". I wouldn't know how to get in touch.

Summary:
- There needs to be something mentioning "Help" and "Contact" somewhere on landing page.
- I would have expected a way to get in touch at the bottom. The buttons are there, but I first had to hover.

**Comment by Axel-Naumann** [comment]
"Help Forum"?

**Comment by Axel-Naumann** [comment]
"About" should have a link to "Contact"

**Comment by hageboeck** [comment]
I guess that should work. Alternatively, put a help link somewhere, and explain that the forum is the primary resource.

Or, and I think I like this best, title the link "Forum / Help"

**Comment by Axel-Naumann** [comment]
As discussed, "Forum & Help" for the button. And the menu, if it's not too ugly.
