### ISSUE TITLE
Update team members

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#413]
We need to update the list of team members.

**Comment by Axel-Naumann** [comment]
From Stefan Wunsch:

> Stefan studied physics at the Karlsruhe Institute of Technology with focus on data analysis, machine learning and software development. Previous projects have been with the Belle and CMS experiments about the integration of modern machine learning in the reconstruction and data analysis toolchain. After his first stay at CERN in 2016 as summer student with the CMS experiment, he returned to CERN in 2018 as PhD working in the ROOT team on machine learning and analysis facilities.

I only have a profile picture too small for the web page. @stwunsch can you provide us with a higher resolution image?

**Comment by couet** [comment]
Updated:
https://root.cern/about/team/
