### ISSUE TITLE
Not able to find information on how to update Web site and where to submit PR

### ISSUE THREAD

**Issue by lmoneta** [root-project/web#42]

**Comment by Axel-Naumann** [comment]
I clicked "For Developers" (top right) and there it is... I'd say it's fine (but see #110 )

**Comment by lmoneta** [comment]
I think we can close there, I agree with #110 and also I think there is another problem, not sure an issue has been already created for this. 
The content shown on the left of the page is not occupying all the space, there when looking in 
"For Developers", the item"Editing the ROOT Website" is not visible .And it is not clear that there is more content, there is no scroll bar. This I find confusing. Should I open another issue for this ?

**Comment by eguiraud** [comment]
@lmoneta I think the problem with "Editing the ROOT website" not being visible in the sidebar will be fixed when/if the "Git primer" section is removed, see #74

**Comment by lmoneta** [comment]
@eguiraud yes this will be saved by #74. But in general it would be nice if we make sure items in the sidebar are not hidden.

**Comment by eguiraud** [comment]
I totally agree, @couet (and all of us) will have to keep an eye out for that. Closing this via #155
