### ISSUE TITLE
root.cern marked as "unsafe" by Google 

### ISSUE THREAD

**Issue by cozzyd** [root-project/web#425]
Currently, when I visited any page hosted at root.cern (but not root.cern.ch...) I get a big scary warning (on Firefox) which directs me to https://transparencyreport.google.com/safe-browsing/search?url=http:%2F%2Froot.cern%2F

![image](https://user-images.githubusercontent.com/9206569/94930711-72a0b780-048c-11eb-8fd9-5d2b9f082d1b.png)

This started this morning. I assume this will eventually be fixed, but as a workaround to make the documentation usable it might be worth changing all the internal links to point to root.cern.ch which is so far unaffected.

**Comment by eguiraud** [comment]
Hi @cozzyd , we are painfully aware, see https://github.com/root-project/web/pull/423

We are working on a solution.

**Comment by Axel-Naumann** [comment]
Request submitted to Google to review; this will take a bit :-(

**Comment by Axel-Naumann** [comment]
That's now https://root.cern/blog/false-positives/ - once you pass the (false positive) red.

**Comment by cozzyd** [comment]
Thanks... https://root.cern.ch/blog/false-positives works (for me) with no warning which might be useful. Amazing how Google can effectively DOS a web page for an unspecified amount of time for a false positive...

**Comment by cozzyd** [comment]
And looks like it's fixed now! (at least on FF).

**Comment by Axel-Naumann** [comment]
Indeed, I have received Google's confirmation a couple of hours ago.
