### ISSUE TITLE
Ubuntu dependencies are out of date

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#431]
On Ubuntu20.04, trying to execute the commands at https://root.cern/install/dependencies/#ubuntu-and-other-debian-based-distributions ,
I get

```
E: Unable to locate package openssl-dev                                              
E: Package 'libqt4-dev' has no installation candidate 
```

`openssl-dev` is substituted by `libssl-dev`, while I could not find a substitute package for `libqt4-dev` (there is no `libqt-dev` or `libqt5-dev` as far as I can tell).

**Comment by eguiraud** [comment]
#522 addresses the libssl-related part of this issue.

**Comment by eguiraud** [comment]
When using just the required packages, xrootd is turned on but cannot be built because of missing `uuid`, and the build system also tries to build LZMA but it fails because it's missing the `aclocal` command (this last one is resolved by installing `autotools-dev` and/or `automake`)

**Comment by ferdymercury** [comment]
For Ubuntu 22 LTS and ROOT latest stable, this issue would be fixed by:  https://github.com/root-project/web/pull/936 and https://github.com/root-project/web/pull/935
