### ISSUE TITLE
Git is now a ROOT dependency

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#432]
`clad` is built with ROOT by default, and the `ExternalProject_Add` step of its build requires a git clone. However, `git` is not listed as a dependency at https://root.cern/install/dependencies .

**Comment by ferdymercury** [comment]
I guess it's slightly different to speak about the prerequisites for running a binary release vs building.

**Comment by eguiraud** [comment]
yes, the list of dependencies has that ambiguity, but build dependencies need to be documented _somewhere_. otherwise how do users know how to build ROOT from source?

**Comment by ferdymercury** [comment]
> yes, the list of dependencies has that ambiguity, but build dependencies need to be documented _somewhere_. otherwise how do users know how to build ROOT from source?

yep, agreed. Maybe using _italic_ for those dependencies that are just for building could be one way to disambiguate

**Comment by guitargeek** [comment]
The page says:
> The page lists the prerequisite packages that need to be installed on the different platforms to be able to configure, build and run ROOT.

So at least this issue is fixed by adding `git` to the prerequisites for all distributions.

The related issue #52 would require additional changes.
