### ISSUE TITLE
Security issue with root.cern, Firefox won't connect

### ISSUE THREAD

**Issue by arekfu** [root-project/web#434]
I cannot access https://root.cern any more. Here is what Firefox has to say about it:

![Screenshot from 2020-10-08 17-48-00](https://user-images.githubusercontent.com/1193708/95482724-b87ae580-098e-11eb-93e8-a1ffab8f2ba8.png)

Note that https://root.cern.ch works (at least until I click on a link that redirects me to root.cern). I am on Firefox 79.0, Ubuntu 16.04.

**Comment by couet** [comment]
That is fixed now.
