### ISSUE TITLE
Add Windows specific information to the "Building ROOT from source" page

### ISSUE THREAD

**Issue by bellenot** [root-project/web#449]
As asked [on the forum](https://root-forum.cern.ch/t/building-root-on-windows-10-again/41895/5), add the latest information concerning Windows 10 (32-bit compilation only, which build options work or not, etc).

**Comment by bellenot** [comment]
The instruction for Windows is there: https://root.cern/install/

**Comment by eguiraud** [comment]
There should be something here as well I think :grimacing: https://root.cern/install/build_from_source/
