### ISSUE TITLE
Adding a class to ROOT is incomplete

### ISSUE THREAD

**Issue by couet** [root-project/web#457]
If one follows the recipe given in the page [Adding a class to ROOT](https://root.cern/manual/adding_a_class_to_root/) it will not work. At least two ingredients are missing:

1. Linkdef.h should be modified in graf2d/graf/inc (the example used is TLine)
2. CMakeLists.txt should be modified in graf2d/graf/ (the example used is TLine)

This page should really be a recipe one can follow step by step to add a new class ABC.

**Comment by eguiraud** [comment]
I don't think this was solved?

**Comment by eguiraud** [comment]
Reopening as there are several issues with "Adding a class to ROOT" and the related "interacting with shared libraries section", see discussion at https://mattermost.web.cern.ch/root/pl/91ya17p5jign8bewomy8x85qoy

**Comment by Axel-Naumann** [comment]
Indeed @eguiraud that's what needs to still happen in manual => functional => io which we will only get to before xmas, so we should leave that open.
