### ISSUE TITLE
https://root.cern.ch/doc/master/group__vmc.html points to non-existing resources at root.cern

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#458]
https://root.cern.ch/doc/master/group__vmc.html points e.g. to https://root.cern.ch/vmc and https://root.cern.ch/geant4-vmc.

Pointed out by [a forum user](https://root-forum.cern.ch/t/broken-links-in-the-vmc-documentation-page/42106).

**Comment by Axel-Naumann** [comment]
The new canonical site is https://vmc-project.github.io/ - the doc needs to be updated. @agheata could you help out?

**Comment by agheata** [comment]
Sure, I'll fix this

**Comment by eguiraud** [comment]
Fixed in ROOT master branch by https://github.com/root-project/root/pull/6760
