### ISSUE TITLE
[About link] Why is the about link in the most prominent location?

### ISSUE THREAD

**Issue by hageboeck** [root-project/web#48]
Usually, about is somewhere at the right or at the bottom or hidden in a menu. Why is the most prominent link in our top bar occupied by "About"?

**Comment by eguiraud** [comment]
I actually was going to open the exact same ticket some days ago, but then I saw https://home.cern, https://www.python.org, https://www.gnu.org ...

**Comment by hageboeck** [comment]
You are right. Maybe preferences changed over time.
