### ISSUE TITLE
Inconsistency adjustments for web page of dependency packages on CentOS 8

### ISSUE THREAD

**Issue by dudarboh** [root-project/web#480]
Packages listed [here](https://root.cern/install/dependencies/) are slightly inconsistent for CentOS 8 as discussed [here](https://root-forum.cern.ch/t/install-dependencies-cmake3/42949/5)

1.  Package `cmake3` is not found.
     CentOS 8 goes with `cmake 3` by default. Package `cmake` should be used instead

2.  Package `r-base` is not found.
     I assume it is just `R` language which can be installed as `sudo yum install R` but not `r-base`

3.  `python-dev` and `python-numpy-dev` also not found.
     CentOS 8 goes with `python3` as default and those packages don't exist.

4. R language is missing in the one-liner:
```
sudo apt-get install gfortran libpcre3-dev \
xlibmesa-glu-dev libglew1.5-dev libftgl-dev \
libmysqlclient-dev libfftw3-dev libcfitsio-dev \
graphviz-dev libavahi-compat-libdnssd-dev \
libldap2-dev python-dev libxml2-dev libkrb5-dev \
libgsl0-dev libqt4-dev
```

**Comment by eguiraud** [comment]
@dudarboh the centos8 dependency list was just updated, please let us know whether things are ok now

**Comment by dudarboh** [comment]
yep, looks good
