### ISSUE TITLE
Better "Get ROOT" section

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#5]
The current user experience when trying to get ROOT on their computers is more confusing than it could be, and there is no mention of a few distribution channels. The "install ROOT" button on the homepage as well as the "Download" button in the top bar bring you to the [download section](https://root-project.github.io/web/download/) of the website, where users are confronted with a choice between a generic ROOT v6.20 link (which brings you to a page where downloads are only one of the sub-options), building the dev version from sources, generic nightlies link, docker, or building from sources again.

The proposal is to substitute `/download` with a refurbished `/install` section. When users land there, they see "Current ROOT stable version: v6.20" and a list of possible installation methods, each linking to more detailed instructions:

* download a pre-compiled binary
  * any ROOT version, including nightly builds
  * several Linux flavours, MacOS and Windows
* use ROOT's distributions on CVMFS
  * any ROOT version, including nightly builds
  * centos7, slc6
* use ROOT on CERN lxplus (do we want this? is it officially supported or just happens to be a recent ROOT version now)
* run ROOT in a Docker container
* compile ROOT from source (for developers and users requiring custom sets of options)

**Supported by the community**
* packages for Gentoo, Fedora and Arch
* homebrew package for MacOS
* conda packages for Linux and MacOS

Maintainers of community packages should be credited, but we should link to external resources for installation instruction as well as user support to make it clear who to report issues to.

**Comment by mxxo** [comment]
For the installation, it could be nice to detect what operating system the user has and funnelling them to the installation steps, e.g.: 

Example: 
![image](https://user-images.githubusercontent.com/40000585/84046231-cf291580-a977-11ea-9a57-220728fd5273.png)

(taken from https://rustup.rs/)

I have zero web experience and don't know how difficult this is to do.

**Comment by eguiraud** [comment]
PRs #93 and #32 addressed most of this issue, with issues #96 , #95 , #94 and probably also #84, #82, #72 , #41 , #44 and #78 tracking what's left to do.

@mxxo I like the suggestion, but that only works for rust because it's advertising _one_ installation method per platform -- unless we want to have one installation _page_ per platform for ROOT, but then a lot of the information at https://root-project.github.io/web/install will be repeated for each platform-specific page..

**Comment by mxxo** [comment]
I think having separate pages per-platform could be nice. It would be more of a maintenance burden but I don't think repeating the common information would be too bad, especially if it's not going to change often (perhaps the situation right now is that it's difficult to tell if something is common information or Linux-specific)? 

Separate pages could let us have the entire lowest-common denominator installation process on a single page (i.e. don't worry about compiling from source, have a separate area altogether for advanced users). For someone just trying to get up and running, a single, platform-specific guide could be very helpful. I don't want to minimize the work involved here though, and completely understand if we don't want to go in this direction.

**Comment by eguiraud** [comment]
I don't think it makes sense to split Linux flavours or even linux flavours from MacOS, most of the content is exactly the same. It might be useful to have a dedicated page for windows though.

**Comment by eguiraud** [comment]
I looked into whether we could switch the `/install` page to a division by platform. It's complicated. The division of installation options by platform is the following:

### Linux (all flavours), MacOS, Windows

* pre-compiled binaries
* building from source

### Linux (all flavours), MacOS

* conda

### Some Linux flavours and MacOS

* LCG releases without dependencies for Ubuntu, Fedora, CentOS, MacOS

### Some Linux flavours

* official packages for Gentoo, Fedora, Arch Linux
* (coming soon) ROOT's .deb package for Ubuntu and Debian-based distros
* LCG views including dependen for CentOS

### MacOS

* homebrew
* macports

### Other ways to use ROOT

* Docker
* installation on CERN LXPLUS

**Comment by stwunsch** [comment]
@eguiraud Are we happy with the install section? Or is there anything to be added?

**Comment by stwunsch** [comment]
The install section looks great to me now, that's why I'm asking. The issues brought up above are basically solved, right?

**Comment by eguiraud** [comment]
Closing this as per discussion: everything we wanted to address for the release has been addressed, @mxxo feel free to make a separate issue out of your feedback
