### ISSUE TITLE
uuid package missing from Fedora dependencies

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#502]
xrootd can't build without `uuid/uuid.h`, brought it by the `uuid` package on Fedora.

**Comment by eguiraud** [comment]
uhm no that's not enough, wip

**Comment by eguiraud** [comment]
looks like the correct package is `libuuid-devel`

**Comment by couet** [comment]
@oshadura : I assigned it to you. Feel free to assign it to somebody else if you think that's not your domain.

**Comment by eguiraud** [comment]
Fixed
