### ISSUE TITLE
Nope: "The usage of ROOT requires in-depth knowledge of C++."

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#516]
At the bottom of https://root.cern/manual/ we have

>     C++
>
>    The usage of ROOT requires in-depth knowledge of C++.
>   For detailed information on C++, refer to C++ language references such as C++ Language Reference.

Could we change that to

> `You need to understand the basics of C++ or Python to use ROOT. As C++ language reference we recommend [cppreference.com](https://en.cppreference.com/w/cpp)`

**Comment by couet** [comment]
Done
