### ISSUE TITLE
Broken link to RooFit in 20 minutes

### ISSUE THREAD

**Issue by ynikitenko** [root-project/web#523]
The link https://root.cern/roofit-20-minutes/ is broken.

I visited it from https://root.cern/doc/master/group__Roofitmain.html - maybe it's not about the site, but about the docs. Anyway thank you for fixing that.

**Comment by couet** [comment]
@lmoneta ; Should we resurrect the page "roof it in 20 minutes" or point to the Roofit chapter in the new Manual ?

**Comment by lmoneta** [comment]
@couet, I think the correct link is this one, https://root.cern/download/doc/roofit_quickstart_3.00.pdf
Is this correct ?

**Comment by couet** [comment]
https://github.com/root-project/root/pull/7538 fix the link as we decided . I will check the link to the QuickStart is present in the manual

**Comment by couet** [comment]
this quick start and others are referenced here: https://root.cern/topical/
