### ISSUE TITLE
Duplication of "Get Started" on front page

### ISSUE THREAD

**Issue by vepadulano** [root-project/web#53]
The front page shows "Get Started" both as a big logo and as a button in the upper-right bar. Similar with "Forum". I think these should be unique on the page

Slightly similar with "Reference". It has a big logo on the front page, but if one clicks on the "Manual" button of the upper-right bar then the reference is found again also on that page. For a non-experienced user maybe the difference between manual and reference is not that clear. I believe both the user guide and the reference should be found with the same path, e.g. both after clicking the "Manual" button of the upper-right bar

**Comment by Axel-Naumann** [comment]
The menu is the same for all pages; the big icons provide quick entry points for the most important pages. See e.g. https://www.python.org/ which has "Docs" in menu and as (sorta text-) icon below. It's common. OK to close?

**Comment by vepadulano** [comment]
Fair enough, it's probably just my taste. I'll close it.
