### ISSUE TITLE
Clarify TMVA User's Guide description

### ISSUE THREAD

**Issue by ynikitenko** [root-project/web#541]
In the documentation (https://root.cern/topical/#tmva) there are two links to TMVA:

- 6 Series (pdf).
- Documentation on the GitHub repository (Updated version for ROOT 6).

From that it's absolutely unclear what the difference between these versions is. Is the second link for 6 series (of ROOT or TMVA?)? Is the first link updated for ROOT 6?
I had to open both links to compare them equal.

What could be improved:
- If they are simultaneously updated, then one link would be enough.
- If you prefer two links, clarify that they refer to one same document. Or that github link is always more recent than the root.cern one. One bullet item with two links inside would convey this meaning better.

**Comment by couet** [comment]
This is a question for @lmoneta . I agree it seems a be redundant. 
Lorenzo can you tell me which one we should keep ? 
I can modify the web page accordingly,
