### ISSUE TITLE
Spectrum manual Forbidden

### ISSUE THREAD

**Issue by ynikitenko** [root-project/web#542]
On the documentation page (https://root.cern/topical/#tspectrum-manual-6-release-cycle) there is a link to 

TSpectrum manual (HTML version)

which leads to 

https://root.cern/root/htmldoc/guides/spectrum/Spectrum.html

which gives 403 error (Forbidden).

Maybe there should exist an automatic broken link testing on root.cern?

**Comment by ynikitenko** [comment]
All TSpectrum manuals' paths refer to root.cern/root and should be fixed.

**Comment by Axel-Naumann** [comment]
> Maybe there should exist an automatic broken link testing on root.cern?

We have it - but it will only find broken links *after* I break them (i.e. now) :-)

Olivier / Johannes, could you fix the Spectrum links, please?

**Comment by couet** [comment]
@Axel-Naumann :  The links to https://root.cern/root/htmldoc/guides are now broken. Your previous message suggests that "you broke" them. What is the new URL where we can find this manuals ?

**Comment by Axel-Naumann** [comment]
Fixed, thanks for reporting!
