### ISSUE TITLE
Add Fit section to the manual

### ISSUE THREAD

**Issue by ynikitenko** [root-project/web#548]
The whole namespace `ROOT::Fit` seems to be missing in the manual.
In the last User's Guide there is a section _5.7 New `ROOT::Fit` classes_.
In the manual there is a section on RooFit (https://root.cern/manual/roofit/). There is also a small section on fitting in the primer (https://root.cern/primer/#functions-and-parameter-estimation) - but I can't find Fitter class in the manual.
Since User's Guide is said to be outdated, please add that section to the manual.

If `ROOT::Fit` is outdated, please write about that in its documentation (https://root.cern/doc/master/group__Fit.html).

**Comment by ynikitenko** [comment]
There is a similar issue about `TTree` in the manual (https://github.com/root-project/web/issues/509), but I decided to open a new one.

**Comment by couet** [comment]
@lmoneta and @JohannesHentrich the section @ynikitenko is referring to in the User's Guide is http://root.cern/root/htmldoc/guides/users-guide/ROOTUsersGuide.html#new-rootfit-classes . Is there something missing in the manual ? Or may be something should be written in the ref guide in the ROOT::Fit name space ?
