### ISSUE TITLE
Minor Style issue on front page (mobile)

### ISSUE THREAD

**Issue by AdvaitDhingra** [root-project/web#561]
Maybe it's because I'm a perfectionist, but when you open the home page the layout of the icons triggers my OCD. 

Is this something that should/could be fixed?

Image:

![IMG_1636](https://user-images.githubusercontent.com/62119114/115151333-b5169400-a06c-11eb-9723-a8d966f48a8c.jpg)

**Comment by couet** [comment]
I am not sure that can be fixed.  I see something different on my iPhone . It is very dependant on the screen size I guess.
Is it really a problem ? a matter of taste I guess....

**Comment by AdvaitDhingra** [comment]
> I am not sure that can be fixed. I see something different on my iPhone . It is very dependant on the screen size I guess.
> Is it really a problem ? a matter of taste I guess....

Yeah, I wasn‘t sure myself. It‘s not that big if an issue.

**Comment by AdvaitDhingra** [comment]
If the style is done in css, perhaps the display could be changed to 
’’’
display: flex;
align-items: center;
justify-content: space-around;
’’’
Could this be a solution in theory?
