### ISSUE TITLE
Compiling macros?

### ISSUE THREAD

**Issue by hageboeck** [root-project/web#57]
I want to compile a macro.
- I looked in manual section, but that didn't help.
I have the feeling that macros should be discussed under "Manual -> Basics".
- The search box directed me to the old website, but that's not what we want.

**Comment by hageboeck** [comment]
Tried to also search for
`site:https://root-project.github.io/web macros`

That's not leading anywhere.

**Comment by couet** [comment]
This done: https://root.cern/manual/interacting_with_shared_libraries/#compiling-root-macros
