### ISSUE TITLE
Add a link to downloadable Reference guides to the documentation

### ISSUE THREAD

**Issue by ynikitenko** [root-project/web#571]
I use offline documentation and find it very convenient.
However, when I recently tried to find an archive for the last ROOT version, I could do that only when I found my old link, not when I tried to find that on the site by navigating "documentation" (actually the menu "manual").
Could you please add the link https://root.cern/reference/ somewhere visible on the site? How one could find that page from the documentation?

**Comment by ynikitenko** [comment]
It seems I found that as the 3rd link from a search on the site.

**Comment by eguiraud** [comment]
Related discussion: https://github.com/root-project/web/issues/11

**Comment by couet** [comment]
https://root.cern/reference/ from https://root.cern/manual/ is not that "hidden"... 
What would be more "visible" for you ? (I guess it is more a matter of personal taste)

**Comment by eguiraud** [comment]
In all fairness the sidebar of /manual might not be the first place you look to find a list of past reference guides or to download the offline version of the latest reference guide.

**Comment by couet** [comment]
Yes it is in the sidebar of /manual ... For me it is fine. What would be a better place ? I am happy to put an extra link elsewhere to make users happy :-)

**Comment by ynikitenko** [comment]
Thank you. Now I can see that. I couldn't find that because the sidebar "toggle menu" was closed in my browser (maybe from a previous session). 

As I can see, the sidebar is rather general (it appears on every page of the manual). So it would be no serious duplication of content if its contents is added to the root page of the documentation?

That page (https://root.cern/manual) describes the documentation in great detail, and it looks like complete, but it is not, which is misleading. I didn't guess to open the sidebar to get even more links to the documentation (usually menus are short, while page contents is large and more complete).

**Comment by couet** [comment]
done with https://github.com/root-project/web/pull/585

**Comment by ynikitenko** [comment]
Beautiful, thanks a lot!
