### ISSUE TITLE
Add documentation in .xz format for download

### ISSUE THREAD

**Issue by ynikitenko** [root-project/web#572]
In another issue (https://github.com/root-project/root/issues/7295) we discussed that an .xz format is rather economical (458M rootdoc.tar.xz vs 701M rootdoc.tar.gz) and modern (is present on major platforms).
I'm opening this issue so that is not forgotten.
Please add an .xz format (or replace .gz) to the download page (https://root.cern/reference/).

**Comment by couet** [comment]
may be something like that:
```
if [ $docdir != "master" -a $docdir != "html602" ]; then
   tarnamegz=${docdir/v/html}.tar
   tarnamexz=${docdir/v/html}.tar
   tar cf $tarnamegz $docdir
   tar cf $tarnamexz $docdir
   gzip $tarnamegz
   xz $tarnamexz
   scp $tarnamegz root.cern.ch:/var/www/root/download/
   scp $tarnamexz root.cern.ch:/var/www/root/download/
fi
```
in:
in https://github.com/root-project/rootspi/blob/master/rdoc/synchtml.sh
