### ISSUE TITLE
Text field unter Search is not recognizable as such

### ISSUE THREAD

**Issue by bernhardmgruber** [root-project/web#59]
When you click the magnifying glass in the top right (for searching), the interface that opens is confusing. I could not straighly see where I should enter my search text.

I tried clicking the blue/grey box unterneath “Enter your search term…”, but I could not enter a text editing mode. It took me a while to find out that “Enter your search term…” is actually a clickable text box and that I can replace this text.

Can you please make it more apparent, that “Enter your search term…” is a text box? Thanks!

**Comment by Axel-Naumann** [comment]
I think the gray bar is confusing; the text box should have some background color different from the page's background color.

**Comment by couet** [comment]
We can surely try to do something different, but I just look at search page and I see that:
1) there is a blinking cursor where you can type.
2) the field where you can type is already active when the page shows up and no click is needed.
Despite the fact I am a bit old fashioned I was not disturbed by this interface.

**Comment by bernhardmgruber** [comment]
@couet you are right! If you let the webpage load completly and look at it for long enough, you can see the cursor blinking ;)

However, if the webpage loads slowly or the user is just fast, one can click the gray bar before one sees the cursor blinking. And then it also stops blinking, because it loses focus.

I think some simple highlighting could already be enough to solve the issue!

**Comment by couet** [comment]
I can also add that the search page looks very similar to the spotlight search box of MacOS. So this way of presenting the search should be quite common. In my case the blinking cursor appears immediately. The MacOS spotlight search box has a lens in addition. I agree that is we find way to make it more obvious it will be good.

**Comment by eguiraud** [comment]
This is the best I could do, but I'm not sure it's better:

![image](https://user-images.githubusercontent.com/10999034/84781354-071f0100-afe7-11ea-9d66-81e9e2851b9b.png)

**Comment by bernhardmgruber** [comment]
Removing the empty bar below the search box is not possible until the search results appear? Otherwise I guess it is already an improvement! Thx!

**Comment by eguiraud** [comment]
> Removing the empty bar below the search box is not possible until the search results appear? 

no idea how -- but @stwunsch showed me how to get rid of the box below, new iteration coming up

**Comment by eguiraud** [comment]
@bernhardmgruber @couet I think the latest iteration makes everyone happy

**Comment by couet** [comment]
Yes it looks good to me.
