### ISSUE TITLE
How to cite ROOT

### ISSUE THREAD

**Issue by bernhardmgruber** [root-project/web#60]
Here is what I tried:

1. I went to About straight away. But then I could not find sth there. I tried license first, but no luck.
2. Now I went through Contribute. Tried everything, no luck.
3. Somewhere in Download?
4. I now read through all the subsection names of all main menu items.
5. I have no clue anymore.
6. I want to try the searchbar, but I cannot click into the box below the “Enter your search term…” (https://github.com/root-project/web/issues/59)
7. A select all on the website revealed, that I need to click the title text. This is a text field.
8. Second search result is a forum post from 2012 giving the answer. That’s 8 years old. Trustworthy?

The website should contain information on how to cite ROOT. Probably somewhere in the About section.

**Comment by bernhardmgruber** [comment]
By now I am just checking out every subpage and I surprisingly found it now. It's on the page news/publications. While publications might fit, how to cite ROOT is definitely not news.

**Comment by Axel-Naumann** [comment]
Might "About" be more intuitive?

**Comment by eguiraud** [comment]
@Axel-Naumann since we are here :smile: what does [our README](https://github.com/root-project/root/#cite) mean with (quoting it verbatim):

We are [![DOI](https://zenodo.org/badge/10994345.svg)](https://zenodo.org/badge/latestdoi/10994345)

Please cite us as

    Rene Brun and Fons Rademakers, ROOT - An Object Oriented Data Analysis Framework,
    Proceedings AIHENP'96 Workshop, Lausanne, Sep. 1996,
    Nucl. Inst. & Meth. in Phys. Res. A 389 (1997) 81-86.
    See also "ROOT" [software], Release vX.YY/ZZ, dd/mm/yyyy,
    (Select the right link for your release here: https://zenodo.org/search?page=1&size=20&q=conceptrecid:848818&all_versions&sort=-version).

I find it very confusing.

**Comment by Axel-Naumann** [comment]
@eguiraud which part is confusing? The part where I don't consistently register releases with Zenodo? :-(

**Comment by eguiraud** [comment]
what does it mean that ROOT _is_ a certain DOI, if I shouldn't use that DOI when I cite ROOT? (what else should I use the DOI for?)

**Comment by Axel-Naumann** [comment]
Ah okay :-) Can you suggest better wording? (This was just colloquial but likely indeed confusing.)

**Comment by eguiraud** [comment]
Maybe, but what is it that you want to communicate exactly? :smile:

**Comment by eguiraud** [comment]
Fixed by #177
