### ISSUE TITLE
Download page contains text that nobody will read

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#62]
https://root-project.github.io/web/install/binary_releases/

has text at the end. That's an easter egg, nobody will scroll there. If it's relevant it should show up at the top.

**Comment by Axel-Naumann** [comment]
I'd suggest:
- strike "Release notes can be found on the respective release page."
- strike "Release notes for old releases can be found here." (the release notes are linked from these older release pages)
- Rephrase "All releases files can be download from here." => "Index of all binaries"

**Comment by couet** [comment]
This page "binary_releases" does not exist anymore. So I guess this issue can be safely closed ? right?

**Comment by Axel-Naumann** [comment]
Agreed
