### ISSUE TITLE
Broken link in snap blog post

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#629]
See e.g. https://github.com/root-project/web/runs/3200524941?check_suite_focus=true

The link is https://snapcraft.io/docs/parallel-installs in the snap announcement blog post.

@MrCarroll any ideas? :)

**Comment by MrCarroll** [comment]
The functionality is still being worked on so the 404 should just be some failure in the documentation/website publishing process.

I'll pass it on and post back here when it's reappeared :)

**Comment by eguiraud** [comment]
Thank you, i thought maybe they just changed the name of that page or something like that

**Comment by MrCarroll** [comment]
The link should be back online now.

**Comment by eguiraud** [comment]
Thanks!! I restarted the build

**Comment by eguiraud** [comment]
Fixed since a while
