### ISSUE TITLE
Dependency on qt5 only present for OpenSUSE

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#632]
See https://root.cern/install/dependencies/#opensuse .

If `libQt5Gui-devel` and `libqt5-qtwebengine-devel` are part of the most common optional dependencies for OpenSUSE, they should be listed for the other linux flavors as well.

Assigning @linev as I think you know what's going on and what we want to do here, feel free to assign this back to me if you don't agree.

**Comment by linev** [comment]
Problem, that I have no idea how these qt5 packages called on other platforms.

**Comment by eguiraud** [comment]
@linev https://pkgs.org might help

**Comment by linev** [comment]
I found for several platforms, some older ones (like CentOS 7) do not provide qt5webengine component
