### ISSUE TITLE
cxx standard C++11

### ISSUE THREAD

**Issue by ferdymercury** [root-project/web#636]
In the webpage https://root.cern/install/build_from_source/#root-stl-backports there are several references being made to C++11, but I think they are obsolete as the minimum standard is now 14 ?

**Comment by couet** [comment]
I see only one:
_ROOT backports certain useful C++ standard library features to make them available in C++11_

**Comment by ferdymercury** [comment]
`can be selected by passing one of 11, 14, 20,… such as `

**Comment by ferdymercury** [comment]
`Turning on C++14 (see Setting the C++ standard) or higher will automatically enable ROOT7.`
here I think it should be 17

**Comment by couet** [comment]
yes that one also (that makes 2) but that the example showing one can elect the C++ version ....

**Comment by couet** [comment]
there is more 14 ....

**Comment by couet** [comment]
_to allow to compile ROOT with C++17 while CUDA code with C++14_

**Comment by couet** [comment]
Can you make a PR and the experts will comment ?

**Comment by ferdymercury** [comment]
> _to allow to compile ROOT with C++17 while CUDA code with C++14_

why is this one incorrect?

**Comment by couet** [comment]
May be it is ok .. you are right ....

**Comment by eguiraud** [comment]
uhm, can we close this when the PR is in?
