### ISSUE TITLE
CMake minimum version

### ISSUE THREAD

**Issue by ferdymercury** [root-project/web#638]
The current CMake minimum version is 3.16, but there are several explanations on version <3.14 on https://root.cern/install/build_from_source/#after-v622

Maybe an 'after v624' section should be added?

See https://github.com/root-project/root/commit/f68ed04667d7c2a4c99ecd44aea1f37252004f82#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a

**Comment by couet** [comment]
I guess @eguiraud is also the best person to ask for this request.
Can you provide a PR as you did for C++14 -> 17 ?

**Comment by eguiraud** [comment]
@ferdymercury we'll take care of this, don't worry and thank you for bringing this up

**Comment by eguiraud** [comment]
We added a comment mentioning that "v6.24 is the last ROOT version that supports cmake <3.16", I think that's enough. Users that are building a recent ROOT with a recent CMake will quickly find instructions, and for the less common usecases they will find comments that explain what is supported where.
