### ISSUE TITLE
Finding information about "Why should I use ROOT?"

### ISSUE THREAD

**Issue by etejedor** [root-project/web#65]
**What I did**

The first thing I looked at was the information under `ROOT is...`, but that only shows a small sentence, and I wanted more information.

So I looked somewhere else, and I clicked on the icon of `Get Started`, with no luck.

So I went back to the main page, and this time I looked in the upper bar, and I saw `About`. Then I clicked there and I found more information about what I can do with ROOT, good!

**Suggestion**

On the front page, in the `ROOT is...` section, I would add a link at the end of the `A modular scientific...`  sentence, which says `Learn more`, and that should bring me to the `About ROOT` page. That would have saved me some back and forth.

**Comment by Axel-Naumann** [comment]
We can decide whether we want "Gallery" or "About" as big icons. In principle they try to address the same audience.

**Comment by Axel-Naumann** [comment]
Make all of " ROOT is ...
A modular scientific software toolkit. It provides all the functionalities needed to deal with big data processing, statistical analysis, visualisation and storage. It is mainly written in C++ but integrated with other languages such as Python. " a link to About?

**Comment by etejedor** [comment]
I think I like the `Learn more` option better, I believe it is more common than having the whole paragraph as a link.
See e.g. Python:
https://www.python.org/

**Comment by Axel-Naumann** [comment]
Addressed by https://github.com/root-project/web/pull/238

**Comment by eguiraud** [comment]
@etejedor I think this can be closed, given the new front page?

**Comment by etejedor** [comment]
Yes!
