### ISSUE TITLE
Release pages should call out full Ubuntu version number

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#66]
E.g. https://root-project.github.io/web/releases/release-62004/

has "Ubuntu 18", but there's 18.04 and 18.10. We need to spell out the full version.

**Comment by couet** [comment]
The last release page does not spell out the full Ubuntu version either: https://root.cern/releases/release-62606/ do we still want to do that? If yes should we edit the old release pages? (I guess not).

**Comment by Axel-Naumann** [comment]
It'd be nice if the release page generator script were to spell this out, yes. Updating the most recent 4 release pages or so would be nice!

**Comment by ferdymercury** [comment]
I think this was fixed by https://github.com/root-project/root/commit/f9f0e5395521da6556a05e4c9fa159f694376492
