### ISSUE TITLE
Remove "compiler version" from download page

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#68]
E.g. https://root-project.github.io/web/releases/release-62004/ mentions "Ubuntu 18 gcc7.5". That's useless / confusing - we always use the default, native compiler, so we should not mention the compiler version. MacOS and Windows should keep the compiler version.

**Comment by couet** [comment]
The latest download pages do not mention the compiler version: https://root.cern/releases/release-62606/ . Do we want to edit the older download pages? I guess not ... In that case, can we close this issue?
