### ISSUE TITLE
Table of contents / Left-right nav bars

### ISSUE THREAD

**Issue by hageboeck** [root-project/web#76]
https://root-project.github.io/web/manual/getting_started_with_root/

Many people expected the table of contents on the right to unfold on the left when a link is clicked. That would also free up some space to display more text.

If one clicks on a different page, it should fold again. This will also help understand that this content is gone from the page that's currently viewed.

Further, the sub pages of e.g. getting started with ROOT should be their own pages. In this case, they would also be findable with `Ctrl + F`.

**Comment by couet** [comment]
The pages "getting_started_with_root" in manual , does not exist anymore... I guess we can close this issue.

**Comment by couet** [comment]
Not relevant anymore.
