### ISSUE TITLE
[forum] legacy tags wrongly converted from phpBB3

### ISSUE THREAD

**Issue by ferdymercury** [root-project/web#784]
When migrating from the old to the new forum , some posts were incorrectly converted and show several issues.

It would be nice to run an "sed" script to fix all those tags so that they are well rendered in the new forum.

See for example:
https://root-forum.cern.ch/t/copying-a-tree/370/8?u=ferhue
The code snippet there is not visible.

I would suggest to crawl through the database and look for:
- [quote*] or [/quote] --> Google already shows like 4k results for this
- [code*] or [/code]
- hljs --> for the invisible snippets, it seems that's one tag that appears in the resulting HTML
- potentially others from https://www.phpbb.com/community/help/bbcode
and then replace accordingly with the current forum's syntax.

The "/quote" and "/code" ones are just aesthetic fixes, but the issue with the invisible snippets is more important as there is no way to rescue what was written in there.

**Comment by couet** [comment]
Just my comment: when I reach such "not well formatted" old posts I usually reformat them by hand if they are of general interest. Note that some old posts were correctly translated.

**Comment by Axel-Naumann** [comment]
This is in a database. Any operation here risks to cause significant side-effects; this needs to be tried on a non-production version first. As such it's significant work, and IMO not well invested compared to what else we could do with that money. I agree with Olivier's workaround.

Is this a reasonable conclusion, @ferdymercury ?

**Comment by ferdymercury** [comment]
Sounds reasonable.

Just one idea regarding the 'invisible snippets'. What about a hybrid approach?

Just grep for "hljs" in the database and see in which urls it pops up. Then edit that by hand one by one on the web browser. If the list is small (20 or so) it might be fixable without too much time effort. Obviously, if it's 200, better forget about it.

Thanks!

**Comment by Axel-Naumann** [comment]
> grep for "hljs" in the database and see in which urls it pops up

That's not something I know how to do... We'd need to write a plugin that inspects the posts and reports which ones have that, and develop and test that filter on a clone of the instance to ensure we are not causing side effects. All in all it seems like a massive amount of work.

Neither Google nor the forum search support searching for `[/code]` or similar, so I don't even know how to get a good estimate even of a subset. We'd probably have to crawl the whole forum and search - but the pages are generated from a database that's hundreds of MB if I remember correctly. I'm afraid that will be fragile, take a long time, and might have a visible performance impact on the forum used in production by thousands of physicists...

If you have other ideas - e.g. what to look for with Google - please let us know!

**Comment by ferdymercury** [comment]
Apparently it is a well-known issue:
https://meta.discourse.org/t/fix-quotes-after-phpbb-import/79133/21?page=2
and some solutions were proposed there.

> Neither Google nor the forum search support searching for `[/code]`

Forum supports it reasonably well, see:

- https://root-forum.cern.ch/search?expanded=true&q=%22%5B%2Fquote%5D%22
- https://root-forum.cern.ch/search?expanded=true&q=%22%5B%2Ful%5D%22
- https://root-forum.cern.ch/search?expanded=true&q=%22%5B%2Fcode%5D%22
- https://root-forum.cern.ch/search?expanded=true&q=%22%5B%2Fcolor%5D%22
- https://root-forum.cern.ch/search?expanded=true&q=%22%5B%2Fi%5D%22%22
- https://root-forum.cern.ch/search?expanded=true&q=%22%5B%2Fb%5D%22
- https://root-forum.cern.ch/search?expanded=true&q=%22%5B%2Fli%5D%22
- https://root-forum.cern.ch/search?expanded=true&q=%22\[%2Fol\]%22

(More exact regex-search can be enabled via forum owner settings, setting "watched words" regex).

**Comment by ferdymercury** [comment]
I have done some statistics, this is what I get, from the about +35k threads in the forum there are:

- 2001 affected by invisible code snippets `<pre><code class="lang-auto"></code></pre>` --> code is completely invisible, info missing for public viewers
- 3202 showing `[/code]` tags --> just aesthetic
- 4177 showing `[/quote]` tags --> just aesthetic
- 280 showing `[/ul]` tags --> just aesthetic
- 286 showing `[/color]` tags --> just aesthetic
- 52 showing `[/i]` tags --> just aesthetic
- 90 showing `[/b]` tags --> just aesthetic
- 115 showing `[/li]` tags --> just aesthetic
- 19 showing `[/ol]` tags --> just aesthetic
