### ISSUE TITLE
Incorporate Courses and Tutorials into Get Started page

### ISSUE THREAD

**Issue by vepadulano** [root-project/web#79]
I believe the Get Started page could be just a list of the useful resources that are now present in the two subpages. 
If a user is trying to look for a tutorial, I belive most of the times they would rather click on a big "Tutorial" button / item in a list than reading through a wall of text

**Comment by couet** [comment]
The Get Started page looks now like that: https://root.cern/get_started/
It points to all the main sources of documentation, courses, and tutorials. I think it is fine now. Can we close this issue?

**Comment by vepadulano** [comment]
I don't think it has changed since the issue was open. But sure, you can close it if you think there's no need to change
