### ISSUE TITLE
`<== Old Drupal Book` tag on "Courses" page

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#81]
`<== Old Drupal Book` markup should be replaced by a more proper tag or better removed. It links to old docs promoting CINT.

**Comment by Axel-Naumann** [comment]
Do you have a link?

**Comment by Axel-Naumann** [comment]
For now link to the frozen Drupal copy that we will upload.

**Comment by couet** [comment]
Let me know when the Drupal frozen copy will be ready.

**Comment by Axel-Naumann** [comment]
It's now here: https://root.cern/d/
