### ISSUE TITLE
MacOS Ventura - Errore while compiling macros

### ISSUE THREAD

**Issue by LudovicoLudovico** [root-project/web#821]
When I compile a macro, since I updated to macOS Ventura I get this error:

root [1] .L particleType.cpp+
Info in <ACLiC>: script has already been loaded in interpreted mode
Info in <ACLiC>: unloading /Users/ludovicofurlanetto/Documents/particles/./particleType.cpp and compiling it
Info in <TMacOSXSystem::ACLiC>: creating shared library /Users/ludovicofurlanetto/Documents/particles/./particleType_cpp.so
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
Error in <ACLiC>: Executing 'cd "/Users/ludovicofurlanetto/Documents/particles" ; c++ -fPIC -c -O3 -DNDEBUG -std=c++14 -Wc++11-narrowing -Wsign-compare -Wsometimes-uninitialized -Wconditional-uninitialized -Wheader-guard -Warray-bounds -Wcomment -Wtautological-compare -Wstrncat-size -Wloop-analysis -Wbool-conversion -m64 -pipe -W -Woverloaded-virtual -fsigned-char -fno-common -Qunused-arguments -pthread -stdlib=libc++  -I$ROOTSYS/include -isysroot "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/" -I"/Users/ludovicofurlanetto/root_install/etc/" -I"/Users/ludovicofurlanetto/root_install/etc//cling" -I"/Users/ludovicofurlanetto/root_install/etc//cling/plugins/include" -I"/Users/ludovicofurlanetto/root_install/include/" -I"/Users/ludovicofurlanetto/root_install/include"   -D__ACLIC__ "/Users/ludovicofurlanetto/Documents/particles/particleType_cpp_ACLiC_dict.cxx" ; c++ -O3 -DNDEBUG "/Users/ludovicofurlanetto/Documents/particles/particleType_cpp_ACLiC_dict.o" -dynamiclib -Wl,-headerpad_max_install_names -m64 -single_module -Wl,-dead_strip_dylibs -undefined dynamic_lookup   "/opt/homebrew/Cellar/zstd/1.5.2/lib/libzstd.1.dylib" "/opt/homebrew/Cellar/lz4/1.9.4/lib/liblz4.1.dylib" "/Users/ludovicofurlanetto/root_install/lib/libRint.so" "/Users/ludovicofurlanetto/root_install/lib/libCore.so" "/opt/homebrew/Cellar/lz4/1.9.4/lib/liblz4.1.9.4.dylib" "/opt/homebrew/Cellar/zstd/1.5.2/lib/libzstd.1.5.2.dylib" "/usr/lib/libpcre.0.dylib /usr/lib/liblzma.5.dylib /usr/lib/libz.1.dylib /usr/lib/libfakelink.dylib /usr/lib/libenergytrace.dylib /usr/lib/libapple_nghttp2.dylib /usr/lib/libcompression.dylib /usr/lib/libnetwork.dylib /usr/lib/libsqlite3.dylib /usr/lib/libMobileGestalt.dylib /usr/lib/libcoretls.dylib /usr/lib/libcoretls_cfhelpers.dylib /usr/lib/libxar.1.dylib /usr/lib/libarchive.2.dylib /usr/lib/libxml2.2.dylib /usr/lib/swift/libswiftCore.dylib /usr/lib/swift/libswiftCoreFoundation.dylib /usr/lib/swift/libswiftDarwin.dylib /usr/lib/swift/libswiftDispatch.dylib /usr/lib/swift/libswiftIOKit.dylib /usr/lib/swift/libswiftObjectiveC.dylib /usr/lib/swift/libswiftXPC.dylib /usr/lib/swift/libswift_Concurrency.dylib /usr/lib/swift/libswift_StringProcessing.dylib /usr/lib/swift/libswiftos.dylib /usr/lib/libpcap.A.dylib /usr/lib/libdns_services.dylib /usr/lib/libbz2.1.0.dylib /usr/lib/libiconv.2.dylib /usr/lib/libcharset.1.dylib /usr/lib/swift/libswift_RegexParser.dylib /usr/lib/libheimdal-asn1.dylib /usr/lib/libCheckFix.dylib /usr/lib/libmecab.dylib /usr/lib/libgermantok.dylib /usr/lib/libThaiTokenizer.dylib /usr/lib/libutil.dylib /usr/lib/libapp_launch_measurement.dylib /usr/lib/libmis.dylib /usr/lib/libxslt.1.dylib /usr/lib/libcmph.dylib /usr/lib/libTLE.dylib /usr/lib/libspindump.dylib /usr/lib/libate.dylib /usr/lib/libexpat.1.dylib /usr/lib/libAudioStatistics.dylib /usr/lib/libSMC.dylib /usr/lib/libperfcheck.dylib /usr/lib/libIOReport.dylib" "/Users/ludovicofurlanetto/root_install/lib/libRIO.so" "/Users/ludovicofurlanetto/root_install/lib/libThread.so" "/Users/ludovicofurlanetto/root_install/lib/libCling.so" "/usr/lib/libncurses.5.4.dylib" "/Users/ludovicofurlanetto/root_install/lib/libMathCore.so" "/Users/ludovicofurlanetto/root_install/lib/libImt.so" "/Users/ludovicofurlanetto/root_install/lib/libMultiProc.so" "/opt/homebrew/Cellar/tbb/2021.7.0/lib/libtbb.12.7.dylib" "/Users/ludovicofurlanetto/root_install/lib/libNet.so" "/usr/lib/libsandbox.1.dylib /usr/lib/libCoreStorage.dylib /usr/lib/libcsfde.dylib /usr/lib/libMatch.1.dylib /usr/lib/libAccessibilityBaseImplementations.dylib  -o "/Users/ludovicofurlanetto/Documents/particles/./particleType_cpp.so"' failed!

PS: before updating it worked fine

**Comment by eguiraud** [comment]
Hello @LudovicoLudovico  , and sorry for the late reply. This github repository is for the development of the ROOT website (https://root.cern/).

To get help regarding ROOT usage, please create a topic on the forum, https://root-forum.cern.ch .
