### ISSUE TITLE
Remove ultra outdated courses

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#83]
There are links to ROOT courses from 2001 and 2010 (see [here](https://root-project.github.io/web/get_started/courses/)):

`Last updated: October 19, 2001 ...`
`Last modified: Tue Mar 30 15:17:15 2010`

It would be beneficial to condense the list of courses to the relevant ones to confuse people less.

**Comment by Axel-Naumann** [comment]
Let's remove at least FNAL, BarBar, Minos.
