### ISSUE TITLE
Libglew1.5 package does not exist on Ubuntu 22

### ISSUE THREAD

**Issue by ferdymercury** [root-project/web#840]
https://root-forum.cern.ch/t/cern-root-v6-26-00-installation-in-ubuntu-22-0/53044

Outdated instructions for this OS in https://root.cern/install/dependencies/

**Comment by ferdymercury** [comment]
If you want to keep the 1.5 for backward-compatibility reasons, then it could be changed with a regex expression so that it is compatible with both:

`sudo apt install '^libglew[0-9]*[.]*[0-5]*-dev$'`

**Comment by couet** [comment]
```
Outdated instructions for this OS in https://root.cern/install/dependencies/
```

I don't know who can help with this. I am not working on ubuntu myself.  Maybe @vepadulano?  
@ferdymercury what fix would you propose on the dependencies page?

**Comment by ferdymercury** [comment]
Replacing what is written now with ^libglew(1.5|)-dev$
