### ISSUE TITLE
TProfile::GetBinError() uses err2=fSumw2 instead of err2=fSumwy2

### ISSUE THREAD

**Issue by ztarem** [root-project/web#857]
see TProfileHelper.h:713
This bug makes GetBinError behave badly - returns 0.0 in some cases, and bogus numbers in others.

**Comment by eguiraud** [comment]
Hello @ztarem , and sorry for the late reply. This github repository is for the development of the ROOT website (https://root.cern).

Please report the bug at github.com/root-project/root/issues/new/ or discuss the issue on the forum, root-forum.cern.ch .
