### ISSUE TITLE
Language bindings of ROOT

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#87]
The page [here](https://root-project.github.io/web/about/) states that "Use ROOT within other languages ROOT provides a set of bindings in order to seamlessly integrate with existing languages such as Python, R and Mathematica."

What is the status of the language bindings to R and Mathematica? If they are not production ready, they should be removed.

**Comment by eguiraud** [comment]
Also note that Mathematica is listed in the actual page about language bindings, but R is: https://root-project.github.io/web/about/integration_with_other_languages/

**Comment by Axel-Naumann** [comment]
We should remove Mathematica; we do not provide bindings.

**Comment by couet** [comment]
fixed
