### ISSUE TITLE
Mathematical Library description is not completed and could be improved

### ISSUE THREAD

**Issue by lmoneta** [root-project/web#88]
I think we could improve the description of Mathematical components.
We could have at the top
 Mathcore
  - mathematical functions
  - algorithms
 -etc...

MathMore

Linear algebra packages
 - matrix package
 - smatrix

Minimization library and classes
 - TMInuit
 - Linear Fitter
 - Minuit2 library
 - genetic minimiser
 - Fumili

Sampler library
 - Unuran
 - Foam

- fftw

-Physics and geometry vectors
 - old vectors
 - genvector

- vecops

**Comment by JohannesHentrich** [comment]
The mathematical library was completed. The contents from the old USer Guide were taken over and additionally new ones were added.
