### ISSUE TITLE
Link between sequential installation steps 

### ISSUE THREAD

**Issue by mxxo** [root-project/web#89]
https://root-project.github.io/web/install/dependencies/
On the install page section: after the required packages, we could add a link to return to the next step in the installation process. You can of course hit the back arrow but it's hard to keep a mental model of where you are in the install pipeline. 

![image](https://user-images.githubusercontent.com/40000585/84049506-87f05400-a97a-11ea-8d9f-c49c52f50e1e.png)

**Comment by couet** [comment]
@mxxo It seems the website structure has changed a bit since the issue was created. Can you please tell again where to want a link to which place?

**Comment by mxxo** [comment]
Hi @couet, I think the idea here was when I was going through the Windows installation process, I had to open this separate page to find the required dependencies, then navigate back to the main installation steps. I thought having a link back to the main install page might be helpful or even to have the dependencies inline with the rest of the installation steps.

**Comment by couet** [comment]
I think it is already quite simple to navigate as you describe, as the link to the dependencies page is available in the navigation menu on the left of the install page, and the link to the install page is always visible on the top bar. If that's ok with you I think we can close this issue.

**Comment by mxxo** [comment]
Sounds good to me!
