### ISSUE TITLE
Remove stale "ideas" section

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/web#895]
https://root.cern/contribute/ contains "Some Ideas" that haven't been updated for years. We should just remove the whole "ideas" mechanism, given that we
- don't receive any interest in this
- don't seem to be able to keep this updated.

**Comment by Axel-Naumann** [comment]
We should probably just replace it with "Fix an [easy](https://root.cern/ideas/2020-06-25-easy-bugs/) bug".

**Comment by Axel-Naumann** [comment]
And the link there should point to Github not Jira. We can use https://github.com/root-project/root/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 for Github.

**Comment by couet** [comment]
I'll do that

**Comment by couet** [comment]
PR [here](https://github.com/root-project/web/pull/896)
