### ISSUE TITLE
About ROOT "Run interactively or build your own application"

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#91]
Such as stated [here](https://root-project.github.io/web/about/):

> You can use the Cling C++ interpreter for your interactive sessions and to write macros, or you can compile your program to run at full speed. In both cases, you can also create a graphical user interface.

What do we want to promote here? Jitting with cling? Compiling the program (this works also without an interpreter)? Why do we mention after that that you can create a GUI?

IMHO, there is no real point in this statement.

**Comment by guitargeek** [comment]
Honestly I see nothing wrong with that statement. We want to promote all these things that you enumerate, and the point with the GUI is that you can build a GUI that can be used either from an interactive session or complied application.
