### ISSUE TITLE
JSRoot plots capture the scrolling

### ISSUE THREAD

**Issue by hageboeck** [root-project/web#92]
When scrolling, plots are capturing the scroll instruction.

If we keep the scrolling one of two things should be done:
1. Change the mouse pointer to people know they are zooming now.
1. Draw a frame around the plot, so it's clear that it hijacked the scrolling.

**Comment by linev** [comment]
There is simple solution:
```
JSROOT.gStyle.ZoomWheel = false;
```
Should be configured after JSRootCore.js script is loaded.
Probably, same can be applied in iPython Notebooks, 
which can have similar problems with scrolling.

**Comment by hageboeck** [comment]
Is there maybe an option to change the mouse pointer?

Or to activate zooming only when in focus?

**Comment by linev** [comment]
> Or to activate zooming only when in focus?

There is other possibility for zooming - clicking and holding mouse left button.
Therefore mouse wheel zooming can be disabled.

I could try to implement "active pad" functionality, but this require extra coding. 
For the moment pad can be made "active" only in interactive session, when ROOT server application is running.

**Comment by ynikitenko** [comment]
I started to create an issue, but found this one. So probably I should copy it here in the comments (like a site feedback).

### Keyboard scrolling doesn't work in the Manual
When I'm reading the manual (e.g. https://root.cern/manual/python), my keyboard can't scroll the page. When I press Page Up, Page Down or arrows, nothing moves (though Home and End work). I can scroll other pages (like the forum) normally.

I'm using Mozilla Firefox on Arch Linux in Gnome Shell.
I tried it with Chromium: first all worked, but when I switched back to Mozilla, it stopped working in Chromium (when I tried it again).

Is this the case for everyone or should I provide more details?

I see a possible reason: a graph inside a plot moves when I press the arrows. However, I always select page text before trying to scroll, so probably the focus should go from the plot (I think that I didn't even touch that)? 

It would be nice if scrolling worked (I have to drag the sidebar manually with the mouse).

**Comment by linev** [comment]
Thanks to remind me - I create PR #579 which should fix scrolling issue.

**Comment by linev** [comment]
Should be fixed now

**Comment by ynikitenko** [comment]
It works, thanks a lot! :)
