### ISSUE TITLE
Release posts (e.g 6.30.02) have 404 links to binary releases via package manager

### ISSUE THREAD

**Issue by MrCarroll** [root-project/web#942]
For at least the 6.30.02 and 6.28.10 release pages, e.g: https://root.cern/releases/release-62810/  - the link under "Binary distributions" 404's, resolving the URL https://root.cern/releases/install/#install-via-a-package-manager rather than https://root.cern/install/#install-via-a-package-manager

I've tried to update this on my end but I'm unfamiliar with Jekyll to be able to confidently do so.

There's possibly other links in other posts that are doing the same, the only ones I have personally looked at are the two above.

**Comment by Axel-Naumann** [comment]
Thanks! We need to understand why that flew under the radar for our link checker!
