### ISSUE TITLE
Missing "System-wide installation" section in "Building ROOT from source"

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#96]
here: https://root-project.github.io/web/install/build_from_source/#system-wide-installation

Formerly, this section was contained in the discussion of "location-independent" and "fix location" installation methods [here](https://root-project.github.io/web/download/building_root/#installation-methods)

**Comment by amadio** [comment]
If you build from source, it's best not to install system-wide. For system-wide installation, it's recommended to use a binary package instead.

**Comment by eguiraud** [comment]
fair enough, then the question is: is there anything from [this paragraph in the old website](https://root-project.github.io/web/download/building_root/#installation-methods) that we should have in the new website? also pinging @Axel-Naumann

**Comment by amadio** [comment]
I see what you mean now. We can document that. Currently using gnuinstall makes ROOT not relocatable, but not setting it and setting `CMAKE_INSTALL_...DIR` breaks ROOT. Ideally, we can merge the two installation modes into one that works in both cases. Also, a better alternative to setting `LD_LIBRARY_PATH` would be to add `-Drpath=ON` to compilation. Many people mess up their systems by adding `source /path/to/oldroot/bin/thisroot.sh` into their bashrc and forgetting it. We should stop encouraging people to do that, and instead just tell them to add `$ROOTSYS/bin` to `$PATH` and set `$PYTHONPATH` to `$ROOTSYS/lib` after configuring with `-Drpath=ON`.

**Comment by eguiraud** [comment]
Ok, I agree things could be better, but for the website we have to document current behavior

I am leaving it up to you to write a short paragraph about these topics (maybe the title "System-wide installation" does not fit the information in which you think people are interested -- feel absolutely free to change it)
