### ISSUE TITLE
Ambiguous "Get started" and "Getting started with ROOT" pages

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#97]
We have both: https://root-project.github.io/web/manual/getting_started_with_root and https://root-project.github.io/web/get_started .

Maybe the former could be called "First steps with ROOT" or something like that? Or: do we need both?

**Comment by Axel-Naumann** [comment]
Changes URLs, we should decide before publication. I was also surprised - I like your suggestion of renaming one.

**Comment by Axel-Naumann** [comment]
Agreed to rename manual page to "First steps with ROOT"
