### ISSUE TITLE
Make images web friendly

### ISSUE THREAD

**Issue by stwunsch** [root-project/web#99]
The images are not optimized for a website, e.g., the splash image has 2.4MB: https://github.com/root-project/web/blob/gh-pages/assets/images/splash.jpg

I'm not sure whether the webserver is clever enough to downscale the image or play other tricks, but in case we deliver such highres images per page load, we should definitely take care of it.

**Comment by couet** [comment]
I will reduce it

**Comment by Axel-Naumann** [comment]
Please make sure we get rid of the aliasing artifacts (steps in diagonal lines) when scaling it down.

**Comment by Axel-Naumann** [comment]
Should be cut and reduced resolution. Also pointed out by #120

**Comment by Axel-Naumann** [comment]
Splash is now 350k - better! And there's #137 which might have an impact.
